### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by scopatz** [JGCRI/gcam-core#10]
Please provide installation instructions from source somewhere, in the readme perhaps.  Also a list of dependencies would be incredibly useful

**Comment by pralitp** [comment]
I think you are looking for the GCAM documentation.  There are many things to consider, you should start by looking at the [Getting Started](http://jgcri.github.io/gcam-doc/user-guide.html) and it sounds like you will also want to follow the links for Compiling GCAM and Running the GCAM data system from there.

**Comment by scopatz** [comment]
Thanks, but this issue was to point out that these are not linked from the repo anywhere...

**Comment by pralitp** [comment]
The link to the getting started is included in the README.md and we would prefer users start from here before moving directly into compiling GCAM or running the data system.

Or is it that you feel it isn't clear that this is the appropriate place to start reading with regards to installing GCAM?

**Comment by scopatz** [comment]
Yeah, it wasn't clear to me that that the getting started link actually contained installation and/or dependency information. I expected a clearly labeled heading, such as with scipy.  https://github.com/scipy/scipy#installation

I thought the getting started would contain information about how to run GCAM and write input files.

Also, I am initially interested in having a conda package for GCAM on conda-forge.  I was planning on doing this myself, but if you all would prefer to add this, that would be even better! Otherwise, I sort of have to start at the compilation stage.

**Comment by rplzzz** [comment]
@scopatz Thanks for your input.  I've entered a task on our work plan, which I hope we can get to sometime in the next few weeks.  Would you be willing to offer some additional feedback on the changes when we get them in place?
