### ISSUE TITLE
whether the settings of GCAM5.2 and GCAM5.1.3 models themselves support the provincial study of air pollutants?

### ISSUE THREAD

**Issue by Jialuyu** [JGCRI/gcam-core#100]
Hello GCAM community,
GCAM USA currently has no provincial studies on air pollutants. the Global Change Assessment Model (GCAM) said “Air Pollutant Emissions Projections does not capture regional and technological heterogeneity and future updates to this are planned” and I want to know whether the settings of GCAM5.2 and GCAM5.1.3 models themselves support the provincial study of air pollutants? If so,Which CSV files need to be province modified? Can you give me an example?

Thank you very much!
Jia

**Comment by ssmithClimate** [comment]
Jia,

The core gcam does not currently support sub-national air pollution emissions because energy systems are represented only at the national level. Versions of GCAM with sub-national resolution (e.g., GCAM-USA) can potentially do this if supplied with inputs to define air pollutant emissions - although that's quite a bit work. The current GCAM-USA release does not contain air pollutant emissions, but this will be included in an upcoming version.

**Comment by Jialuyu** [comment]
thank you! and I want to know when will the version containing air pollutant emissions be released? I'm in a bit of a hurry. I've been doing research on the provinces of air pollutants, If it's convenient for you, can you give an example of a state? For example, after the addition of air pollution study in New York (or other states), corresponding to the modified CSV situation? I would like to create CSV of air pollutants in provinces of my country by imitating your example. Many thanks for your help!

**Comment by ssmithClimate** [comment]
Jialuyu - what country are you interested in? We only have state level detail in the energy system for the USA in the current. release. If you're interested in a different country, then you would need to build province level energy system detail, which is a very large project.

**Comment by Jialuyu** [comment]
Sorry, I gave the wrong example earlier (not city level, not New York). I only want the state level detail of air pollution emissions in the energy system for the USA. 
I have another question. Can the existing version of GCAM be plugged into a module that shares the nation's air pollution emissions data proportionally to the states (Although the proportional allocation is rough, it may represent the emissions of air pollutants by the provinces)? So I might not have to build a province level energy system detail. 
Thanks a lot!

**Comment by Jialuyu** [comment]
Sorry, I gave the wrong example earlier (not city level, not New York). I only want the state level detail of air pollution emissions in the energy system for the USA. I'll wait for the latest release.

Thanks a lot!
