### ISSUE TITLE
XML generation problem

### ISSUE THREAD

**Issue by Jialuyu** [JGCRI/gcam-core#103]
Hello GCAM community,
When I generated the XML file through R project in GCAM 5.2, the following error occurred:

**Error: Assigned data `min(MODEL_BASE_YEARS)` must be compatible with existing data.
i Error occurred for column `logit.year.fillout`.
x Can't convert <double> to <character>.
Run `rlang::last_error()` to see where the error occurred.**

Is CSV (the file used to generate XML) in GCAM 5.2 completely correct? How can I correct this error?
I've tried different versions of GCAM. When different versions of GCAM generate XML, there will be different errors. I think this is related to the CSV file that GCAM generates XML. I don't think it's a technical problem with R. But I'm not sure. I hope you can help me solve this problem.

Thank you very much!

**Comment by marideeweber** [comment]
I could previously run driver() and generate the XMLs without error, but after running GCAM 5.2 Release today I received the same error as above. Additionally, the full "Can't convert" comment is
`Can't convert <double> to <character>`

**Comment by pkyle** [comment]
This is related to an update in the tidyr package that increases the strictness of column types. As we're currently in the middle of a number of core model improvements and bugfixes, I don't know when the next release will be available, but for now, this specific error can be fixed by modifying the `set_years()` function in `module_helpers.R`:

```
set_years <- function(data) {
  ## silence package check.
  . <- NULL

  assert_that(is_tibble(data))
  year_recode <- c("start-year" =  min(MODEL_BASE_YEARS),
                   "final-calibration-year" = max(MODEL_BASE_YEARS),
                   "final-historical-year" = as.numeric(max(HISTORICAL_YEARS)),
                   "initial-future-year" = min(MODEL_FUTURE_YEARS),
                   "initial-nonhistorical-year" = min(MODEL_YEARS[MODEL_YEARS > max(HISTORICAL_YEARS)]),
                   "end-year" = max(MODEL_FUTURE_YEARS))
  if(nrow(data)) {
    data %>%
      dplyr::mutate_if(funs(any(. %in% names(year_recode))), funs(dplyr::recode(., !!!year_recode, .default=suppressWarnings(as.numeric(.))))) ->
      data
  }
  data
}
```

**Comment by Jialuyu** [comment]
thank you very much!



------------------
-----贾璐宇
-----中国人民大学 &nbsp;环境学院 &nbsp; 人口、资源与环境经济学 &nbsp;
-----email:627688213@qq.com
-----仰望星空，脚踏实地



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JGCRI/gcam-core"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 凌晨4:28
收件人:&nbsp;"JGCRI/gcam-core"<gcam-core@noreply.github.com&gt;;
抄送:&nbsp;"Jialy"<627688213@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JGCRI/gcam-core] XML generation problem (#103)





 
This is related to an update in the tidyr package that increases the strictness of column types. As we're currently in the middle of a number of core model improvements and bugfixes, I don't know when the next release will be available, but for now, this specific error can be fixed by modifying the set_years() function in module_helpers.R:
 set_years <- function(data) {   ## silence package check.   . <- NULL   assert_that(is_tibble(data))   year_recode <- c("start-year" =  min(MODEL_BASE_YEARS),                    "final-calibration-year" = max(MODEL_BASE_YEARS),                    "final-historical-year" = as.numeric(max(HISTORICAL_YEARS)),                    "initial-future-year" = min(MODEL_FUTURE_YEARS),                    "initial-nonhistorical-year" = min(MODEL_YEARS[MODEL_YEARS &gt; max(HISTORICAL_YEARS)]),                    "end-year" = max(MODEL_FUTURE_YEARS))   if(nrow(data)) {     data %&gt;%       dplyr::mutate_if(funs(any(. %in% names(year_recode))), funs(dplyr::recode(., !!!year_recode, .default=suppressWarnings(as.numeric(.))))) -&gt;       data   }   data }
