### ISSUE TITLE
Oil Credits and Bio Feedstock Limit

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#104]
Hi 
I noticed the "liquid_limits.xml" file is a policy-portfolio-standard with an "oil-credits" tag. 
Going by the label of the file I am presuming this XML file places a constraint on liquid biofuels. 
Can kindly explain how the XML file works and how the oil-refining sector is linked to the limiting bio-feedstocks in GCAM.  

Thank you in advance.

**Comment by pkyle** [comment]
Liquids_limits imposes a constraint on the portion of bio-liquids that can be used by oil power plants and industrial feedstocks. The fractions are set in `constants.R`:
```
energy.OILFRACT_ELEC            <- 1.0
energy.OILFRACT_FEEDSTOCKS      <- 0.8
```
Basically, each unit of output of the "oil refining" technology within the "refining" sector produces one credit, and the oil power plant and feedstocks technologies consume credits according to coefficients computed as these assumed fractions multiplied by their liquid fuel energy input-output coefficients. It tends to be only relevant in scenarios with deep decarbonization where liquid fuels are primarily produced from biomass.

**Comment by RawisWar** [comment]
Thank you.
