### ISSUE TITLE
No visitors folder for hector integration

### ISSUE THREAD

**Issue by ypwong22** [JGCRI/gcam-core#105]
Update: sorry, I think the result is me copying the wrong hector model files. 

I found out from a previous issue that using https://github.com/JGCRI/hector/releases/tag/v2.0.0 removed this compiling error. But the current link in the build documentation points to gcam-integration, which does not work (https://jgcri.github.io/gcam-doc/gcam-build.html#43-building-with-visual-studio). 

-------------------------------------

Hello GCAM community,

I am trying to build GCAM v5.2 from source following the instructions at https://jgcri.github.io/gcam-doc/gcam-build.html. 

One of my build error is 

Error (active)	E1696	cannot open source file "visitors/csv_outputstream_visitor.hpp"	objects-main	C:\Users\admin\Documents\GCAM\gcam-core-gcam-v5.2\cvs\objects\climate\source\hector_model.cpp	64	

I think this line implies I need a 

"C:\Users\admin\Documents\GCAM\gcam-core-gcam-v5.2\cvs\objects\visitors/csv_outputstream_visitor.hpp" 

file? But this folder/file does not exist in GCAM v5.2. 

Could you help me with the problem? Thanks. 

Thank you.
Yaoping

**Comment by kvcalvin** [comment]
@ypwong22: Has this been resolved?

**Comment by ypwong22** [comment]
> 
> 
> @ypwong22: Has this been resolved?

Yes, I can build the model using hector 2.0. Perhaps you would want to change the link in gcam docs.
