### ISSUE TITLE
Please add adjusted-coefficient element to next GCAM core update

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#107]
Hello,

I've been working with GCAM for several years now and have been waiting for a model update that allows for the use of adjusted-coefficients. This is required in order to run a renewable energy standard in the power sector correctly, which is likely to be one of the highest priority policies for users of GCAM. It seems like this is not a major upgrade and it would significantly enhance the usability of GCAM. @rjplevin has recompiled GCAM in several instances to enable this feature. We first discussed it with @pralitp in January 2019 and it would be really nice for this to make it into the next version, since it's been nearly 1.5 years since first discussed.

**Comment by pralitp** [comment]
I think this has been in since 5.3.  But certainly in 5.4
