### ISSUE TITLE
Issues when running GCAM on pic

### ISSUE THREAD

**Issue by felipefeijoo** [JGCRI/gcam-core#11]
It is likely you will get errors like:

./gcam.exe: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./gcam.exe)

To resolve this, make sure you have the correct c++ compiler added. This is gcc 5.2.0

**Comment by rplzzz** [comment]
That is correct.  You do that with `module load gcc/5.2.0` (though I usually use 6.1.0 myself).  Also, certain modules on PIC (e.g., openmpi) will silently load one of the gcc-4 modules, so you might want to make sure that loading the correct gcc module is the last thing you do in your job script.
