### ISSUE TITLE
GCAM v5.2 Release - trouble running GCAM

### ISSUE THREAD

**Issue by Rit3755** [JGCRI/gcam-core#110]
I am trying to run the GCAM v5.2 release package on a windows operating system and I keep getting a VCRUNTIME140_1.dll error when I try to run GCAM (screenshot below). Any guidance as to how I should proceed would be appreciated. Thanks.

![Annotation 2020-07-14 105121](https://user-images.githubusercontent.com/68288477/87440500-0ebecf00-c5c0-11ea-9371-1ff9a0a74371.png)

**Comment by pralitp** [comment]
I think you need to install the Microsoft Visual C++ redistributable from:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

You will need the version for `x64` and 2015 / 2017 / 2019.
