### ISSUE TITLE
Harvest and Post-Harvest Loss of agriculture products

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#117]
Hi 

Does GCAM capture harvest and post-harvest loss of agriculture products? 
If it is possible which XML file or tag should I change to model these losses?

Thank you in advance.

**Comment by pkyle** [comment]
Information on agricultural product losses isn't found in any single, convenient place. Any losses related to the harvest, that would result in the products not making it to market, wouldn't show up under production or harvested area to begin with. In the upstream supply chain, food processing and distribution losses that are estimated by the FAO as "waste" show up in GCAM's "NonFoodDemand" sectors. Losses related to food preparation and consumption aren't tracked by FAO, and would end up in the corresponding "FoodDemand" sectors.
Note that there is some information about the non-harvested parts of the crops, and I'm not sure if that would be of interest here. It's used in GCAM for constructing residue biomass supply curves and estimating cropland vegetation carbon content. Under any agricultural production technology there's a section in the XML for the `residue-biomass-production` that has the assumed `harvest-index`, equal to the mass of the harvested portion of the plant divided by the total above-ground biomass. Harvest index assumptions are found in `inst/extdata/aglu/Various_ag_resbio_data.csv`

**Comment by sirwentemi** [comment]
Thanks for the clarification
