### ISSUE TITLE
Carbon tax policy files appear not to work

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/gcam-core#118]
The pygcam tutorial uses the C tax files as an example, however in v5.2 the policy cases now show no change from the baseline. I see that in v5.2, the name of the "ghgpolicy" was changed from "CO2" to "CO2_LTG". Changing this back to "CO2" does not result in changes from the baseline.

Running the with a carbon tax file and the global_uct.xml file produces a message like this for all regions:

"Linked market CO2_LUC in USA could not be linked to CO2"

This is also unchanged by changing the name of the "ghgpolicy" back to "CO2".

Please confirm that these files behave as expected and let me know if there is any change in the way they should be used.

Thanks,
Rich

**Comment by kvcalvin** [comment]
The files do behave as expected, but they have to be read in in a specific order. We recommend starting from the `configuration_policy.xml` file when running carbon taxes.
