### ISSUE TITLE
Estimating effects on labor/job creation 

### ISSUE THREAD

**Issue by lucasingamba** [JGCRI/gcam-core#12]
Hello,

Can I use GCAM to estimate the impacts of a policy on direct, indirect, and induced labor of a region (i.e. direct: labor related to the manufacture of a specific tech, indirect: labor involved in supply chain of the tech, and services that support general economy like doctors and such?)

**Comment by kvcalvin** [comment]
Unfortunately, GCAM does not track labor and cannot be used for this purpose.
