### ISSUE TITLE
GCAM 5.3 reference case: error in solving for year 2025

### ISSUE THREAD

**Issue by sshreekar** [JGCRI/gcam-core#120]
Trying to run a reference case using the most recent code (GCAM 5.3) from the github. It is giving error for solving year 2025. I tried to increase the iter limit to 10000 now to see if this is an issue.
Below is the error message:
Writing restart file: ./restart/restart.5... Done.
Period 6: 2025
Number of active state values: 1624996
Starting Solution. Solving for 1156 markets.
ERROR:Model did not solve period 6 within set iteration 2583
ERROR:Currently Unsolved Markets: 
ERROR:Unsolved Part 1: Solvable Markets
ERROR:X,         XL,        XR,        ED,        EDL,       EDR,       RED,       brk, Supply,    Demand,    Mrk Type,  Market,                             
ERROR:0.410626  , 0.410626  , 0.410626  , -0.0352175, 0.00842779, -0.0352175, 0.441491  ,	1  , 0.114987  , 0.0797696 , Normal    , South America_NorthernDDGS and feedcakes, 
ERROR:0.338539  , 0.338535  , 0.338539  , -0.00340114, 0.000404531, -0.00340114, 0.0226125 ,	1  , 0.153811  , 0.15041   , Normal    , South America_NorthernOilCrop       , 
ERROR:1.24985   , 1.24979   , 1.24985   , -0.00648823, 0.00300788, -0.00648823, 0.120909  ,	1  , 0.0601505 , 0.0536623 , Normal    , South America_Northernbiomass       , 
ERROR:0.00322671, 0.00322671, 0.00322671, -0.000107018, -9.6054e-05, -9.6054e-05, 0.0343039 ,	0  , 0.00322671, 0.00311969, Trial-Value, South America_Northernresid-internal-gains-trial-market-trial-supply, 
ERROR:0.103594  , 0.103594  , 0.103594  , -0.0037691, -0.00262385, -0.00262385, 0.0013928 ,	0  , 2.70991   , 2.70614   , Normal    , South America_NorthernRice          , 
ERROR:3.40911   , 3.40911   , 3.40911   , -0.00428393, -0.00316459, -0.00316459, 0.00125819,	0  , 3.40911   , 3.40482   , Price     , USAtraded unconventional oil        , 
ERROR:14.2592   , 14.2592   , 14.2592   , 0.0342405 , -0.00401195, -0.00401195, 0.00239555,	0  , 14.2592   , 14.2934   , Demand    , USAtraded unconventional oilDemand_int, 
ERROR:1.99738   , 1.99738   , 1.99738   , -0.000498391, -0.000229268, -0.000229268, 0.00167215,	0  , 0.298553  , 0.298054  , Normal    , South Asiaunconventional oil        , 
ERROR:2.00258   , 2.00258   , 2.00258   , -0.000502954, -0.000234941, -0.000234941, 0.00169445,	0  , 0.297327  , 0.296824  , Normal    , Pakistanunconventional oil          , 
ERROR:0.014738  , 0.014738  , 0.014738  , -0.00128387, 7.62834e-05, 7.62834e-05, 0.00159657,	0  , 0.80543   , 0.804146  , Normal    , TaiwanSugarCrop                     , 
ERROR:0.142223  , 0.142223  , 0.142223  , 0.00172693, 7.0008e-05, 7.0008e-05, 0.00708263,	0  , 0.2421    , 0.243827  , Normal    , TaiwanDDGS and feedcakes            , 
ERROR:0.295987  , 0.295987  , 0.295987  , -0.00166959, -0.000815021, -0.000815021, 0.00120857,	0  , 1.38312   , 1.38146   , Normal    , South America_NorthernRootTuber     , 
ERROR:1.17289   , 1.17289   , 1.17289   , -0.000536096, -0.000466959, -0.000466959, 0.00107307,	0  , 0.500128  , 0.499592  , Normal    , South Asiabiomass                   , 
ERROR:Unsolved Part 2: Unsolvable Markets Not Cleared
ERROR:X,         XL,        XR,        ED,        EDL,       EDR,       RED,       brk, Supply,    Demand,    Mrk Type,  Market,                             
ERROR:

**Comment by pkyle** [comment]
Thanks for the posting--it's interesting, I've seen this sort of instability in several development branches but hadn't realized we had it in the core model. This was just running a reference scenario?
In any case, what I'd recommend is, in the following file:
`input/gcamdata/inst/extdata/energy/A_regions.csv`
in the row for GCAM_region_ID 25, re-set the field `biomassOil_tech` (i.e., the region's default assumed biodiesel feedstock) from "OilCrop" to "PalmFruit". That will remove the `DDGS and feedcakes` market altogether from South America_Northern, and it is this market that is causing the solution instability.

**Comment by sshreekar** [comment]
Thanks. Well, raising the default iteration limit to "10000" solved the reference case. It took 6219 iterations, in the solver config file supplied with the core model in github has "1000".

Period 6: 2025
Model solved normally. Iterations period 6: 3572. Total iterations: 6219
