### ISSUE TITLE
config XML file tags should be unique

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/gcam-core#121]
Several versions ago you guys made all the names for the ScenarioComponents in configuration.xml unique so they could be found and operated on automatically.

In 5.2, the configuration_usa.xml uses the names socio_usa, ind_usa twice each. It would be helpful if the second of each of these had a different name. Thanks!

**Comment by mbins** [comment]
Hi rjplevin, thanks for flagging this issue.  The duplicate socio_usa names has been resolved as of the latest release; I will make sure the duplicate ind_usa names are addressed before the next one.
