### ISSUE TITLE
Generate xml input files

### ISSUE THREAD

**Issue by github-wbx** [JGCRI/gcam-core#123]
Hello GCAM community,
I want to generate xml input files through R file under the gcamdata folder in the gcam-core-gcam-v5.3. The 2019 Tutorial Slides mentioned that we can use R file "zchunk_batch*" to generate xml input files. But I cannot find a way to achieve it. I hope you can give me some suggestions to solve this problem.

Thank you very much!

**Comment by pkyle** [comment]
I'm not sure exactly what you're trying to do, so I'll just write a short description, working backwards. To generate one selected XML file, use the following command, to construct modeltime.xml, for example:
`driver(stop_after = "module_modeltime_batch_modeltime_xml")`
To make a new XML file, built from various data tables, the best way is to just copy a similar or simple existing `zchunk_batch_*_xml.R` file, re-name it, the function name, all of the data tables therein and the name of the XML output file. Presumably the data tables being used in the new one would be constructed elsewhere, but that isn't necessary; i.e., you could do some data processing in your new `zchunk_batch_*_xml.R` file to create the data tables that will be read to XML. When using `add_xml_data()`, the IDstring (second argument, in quotes) needs to be an item in `LEVEL2_DATA_NAMES`, and each data table has to have all of the necessary column names expected by `LEVEL2_DATA_NAMES[["*"]]`.

**Comment by github-wbx** [comment]
Sorry for not expressing the problem clearly. 
I have run the GCAM model via  GCAM 5.2 Package, and the lastest release GCAM 5.3 update final calibration year to 2015, so I want to run the model with 2015 calibration year. Compared to GCAM 5.2, GCAM 5.3 just released the gcam source code and no gcam-Windows-Package, and the difference between code and Package is that there is lack of xml file under the input folder(See attached figure). My understanding is that the lack of xml file in gcam 5.3 souce code need to be generated by  zchunk_batch_*_xml.R file under the R folder, So my qeusiton is how to generate xml input file from zchunk_batch_*_xml.R file, by a command prompt, RStudio or other ways.

Thank you very much!
![Package](https://user-images.githubusercontent.com/60533517/98761957-8509fb80-2411-11eb-98fc-b78560f250c3.jpg)
![source code](https://user-images.githubusercontent.com/60533517/98761964-889d8280-2411-11eb-9b5e-c1bc6abe8767.jpg)

**Comment by pkyle** [comment]
Oh I see! There are a few options. From a command prompt in a Git Bash terminal window, change directories (cd) to the root directory of the workspace `gcam-core-gcam-5.3`, and key in:
`make xml`
That will build the full set of XML files, if you have a recent version of R installed, and all of the necessary R packages are installed, in versions that are compatible with the current R code base. See `input/gcamdata/DESCRIPTION` for a list of packages to install, using the `install.packages()` function.
XML files can also be built from Rstudio, by opening up the project file `input/gcamdata/gcamdata.Rproj`, and executing the following commands:
```
devtools::load_all(".")
driver()
```
Note that the gcamdata repository is held and documented in a different repository than gcam-core, though the documentation for the former is more geared towards the construction and initial implementation of the gcamdata package. Still see for example https://github.com/JGCRI/gcamdata/wiki/Getting-Started

**Comment by github-wbx** [comment]
Thank you for your reply. I tried to build the XML files from RStudio, and installed all of the necessary R packages, but when executed the command: devtools::load_all("."), it showed  error message:
> devtools::load_all(".")
Loading gcamdata
> driver()
GCAM Data System v5.1
Found 349 chunks
Found 3202 chunk data requirements
Found 1832 chunk data products
1128 chunk data input(s) not accounted for
|================================================================================================| 100% 1 MB
|===============================================================================================| 100% 57 MB
|===============================================================================================| 100% 57 MB
[1] "module_aglu_LA100.0_LDS_preprocessing"
 error: L100.Land_type_area_ha is being returned grouped. This is not allowed; please ungroup() 
9.stop(assertError(attr(res, "msg"))) 
8.assert_that(is.null(dplyr::groups(dots[[dname]])), msg = paste0(dname, 
    " is being returned grouped. This is not allowed; please ungroup()")) at utils-data.R#240
7.FUN(X[[i]], ...) 
6.lapply(names(dots), function(dname) {
    if (is_tibble(dots[[dname]])) {
        assert_that(is.null(dplyr::groups(dots[[dname]])), msg = paste0(dname, 
            " is being returned grouped. This is not allowed; please ungroup()")) ... at utils-data.R#233
5.return_data(L100.Land_type_area_ha, L100.LDS_ag_HA_ha, L100.LDS_ag_prod_t, 
    L100.LDS_value_milUSD, L100.MIRCA_irrHA_ha, L100.MIRCA_rfdHA_ha, 
    L100.Mueller_yield_levels, L100.Ref_veg_carbon_Mg_per_ha, 
    L100.Water_footprint_m3) at zchunk_LA100.0_LDS_preprocessing.R#186
4.module_aglu_LA100.0_LDS_preprocessing("MAKE", list(`aglu/LDS/Land_type_area_ha` = structure(list(
    iso = c("abw", "abw", "abw", "abw", "abw", "abw", "abw", 
    "abw", "abw", "abw", "abw", "abw", "abw", "abw", "abw", "abw", 
    "abw", "abw", "abw", "abw", "abw", "abw", "abw", "abw", "abw",  ... 
3.do.call(chunk, list(driver.MAKE, all_data)) at driver.R#16
2.run_chunk(chunk, all_data[input_names]) at driver.R#292
1.driver()

**Comment by evasinha** [comment]
I faced similar error message very recently. It was caused since I has using a more recent version of dplyr. Downgrading dplyr (I now have version 0.8.5) had fixed the problem for me. You can downgrade dplyr using the following command: `install_version("dplyr", version = "0.8.5", repos = "http://cran.us.r-project.org")`.

**Comment by github-wbx** [comment]
@evasinha Thank you for your suggestion, I executed the following commands:
`devtools::install_version("dplyr", version = "0.8.5", repos = "http://cran.us.r-project.org")`

But the result seems that failure to downgrade or compilation dplyr:

> devtools::install_version("dplyr", version = "0.8.5", repos = "http://cran.us.r-project.org")
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/dplyr/dplyr_0.8.5.tar.gz
Installing 1 packages: plogr
试开URL’http://cran.us.r-project.org/src/contrib/plogr_0.2.0.tar.gz'
Content type 'application/x-gzip' length 7795 bytes
downloaded 7795 bytes

* installing *source* package 'plogr' ...
** package 'plogr' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'plogr'
    finding HTML links ... OK
    plogr-package                           html  
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (plogr)

The downloaded source packages are in
        ‘C:\Users\ibm\AppData\Local\Temp\RtmpAjuvtV\downloaded_packages’
* installing *source* package 'dplyr' ...
** package 'dplyr' successfully unpacked and MD5 sums checked
** using staged installation
** libs
"c:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"E:/R/R-40~1.3/include" -DNDEBUG -I../inst/include -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_DPLYR -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT -DBOOST_NO_AUTO_PTR  -I'E:/R/R-4.0.3/library/BH/include' -I'E:/R/R-4.0.3/library/plogr/include' -I'E:/R/R-4.0.3/library/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
sh: c:/rtools40/mingw64/bin/g++: No such file or directory
make: *** [E:/R/R-40~1.3/etc/x64/Makeconf:229: RcppExports.o] Error 127
ERROR: compilation failed for package 'dplyr'
* removing 'E:/R/R-4.0.3/library/dplyr'
* restoring previous 'E:/R/R-4.0.3/library/dplyr'
Erroe: Failed to install 'unknown package' from URL:
 Warning in install.packages:installation of package ‘C:/Users/ibm/AppData/Local/Temp/RtmpAjuvtV/remotes16806e252872/dplyr’ had non-zero exit status
>

**Comment by github-wbx** [comment]
@evasinha Thank you for your suggestion, I solved the problem successfully in RStudio by executing the following commands: 
`devtools::install_version("dplyr", version = "0.8.5", repos = "http://cran.us.r-project.org")`
