### ISSUE TITLE
Issues when running forcing target in GCAMv5.3

### ISSUE THREAD

**Issue by Silviameteoro** [JGCRI/gcam-core#124]
Hi,

I am having some issues when trying to run GCAM v.5.3 using a forcing target. I am setting the configuration file similarly to what I used to do in prior GCAM versions (setting find-path mode = 1 and calling /input/policy/carbon_tax_0.xml). Examining the log file, it seems the forcing target run proceeds as expected (although the runs goes much faster than in prior GCAM versions, about 2 hours). However, the outputs are equal to the ones in the reference scenario.

Could you please help to understand what has changed in this version and to set up the forcing target run? I attached the configuration file (config-RCP) I used and the log file (slurm-15446972). About the log file, one thing that calls attention is the ERROR that appeared at the end of the log:

All model periods solved correctly.
Model run completed.
ERROR:Failed due to invalid trial price generated by solver.
Printing output
Starting output to XML Database.
Model run completed.
Model exiting successfully.
./gcam.exe -Cconfig-$job.xml -Llog_conf.xml  5893.88s user 14.31s system 99% cpu 1:39:17.79 total
Sun Nov 15 01:00:56 PST 2020

Thanks for any advice.

[config-RCP26.txt](https://github.com/JGCRI/gcam-core/files/5543045/config-RCP26.txt)
[slurm-15446972.txt](https://github.com/JGCRI/gcam-core/files/5543041/slurm-15446972.txt)

**Comment by glacierRing** [comment]
I also confronted with this problem. 
It happened when I ran GCAMv5.3 with batch_SSP_SPA23.xml and tried to force SSP3 scenarios to reach 4.5W/m2 in 2100. (without changing default xml input files in GCAMv5.3.) 
While batch_SSP_SPA5.xml ran successfully with same xml input. I am wondering what lead to the difference.

**Comment by kvcalvin** [comment]
Hi all,

We've changed the policy set up a little bit in recent versions to better represent the near-term. There is a new configuration file (configuration_policy.xml) that includes the necessary files to get target finder to work. 

Try using that configuration OR adding the extra add on files at the end to your existing configuration. Please note that order matters with these files.
