### ISSUE TITLE
batch_SSP_SPA.xml running problems in GCAMv5.3

### ISSUE THREAD

**Issue by glacierRing** [JGCRI/gcam-core#125]
hi！
I try to run the batch_SSP_SPA3.xml in GCAMv5.3. Which configuration file should I use, is configuration_ref.xml OK?
I ran several batch_SSP_SPA.xmls with configuration_ref.xml. Unreasonable error appeared in several certain SSP-RCP combinations. I will explain this problem below.

There is the output of SSP-RCP combinations with error:
1 RCP45SSP3 it seems that every dispatch solved correctly ,while I got the error that invalid trial price generated by solver.
[jobRCP45SSP3.txt](https://github.com/JGCRI/gcam-core/files/5560717/jobRCP45SSP3.txt)

2 RCP26SSP2 following warnings appeared repeatedly and calculation ended as it reached iteration limits.
    Tue Nov 17 22:37:27 2020:WARNING:printLogHeader: hector version 2.5.0
    Tue Nov 17 22:37:27 2020:WARNING:setData: Disabling onelineocean
    Tue Nov 17 22:37:27 2020:WARNING:prepareToRun: Disabling onelineocean
     it followed by this one:
    Error setting price in marketplace for: CO2_LTG, value: -nan
    Error setting price in marketplace for: CO2_LTG, value: -nan
    Error setting price in marketplace for: CO2_LTG, value: -nan
[jobRCP26SSP2.txt](https://github.com/JGCRI/gcam-core/files/5560721/jobRCP26SSP2.txt)

3  Following error sometimes appears, I wonder it is the problem of the version of Hector.
    ERROR:Receieve hector exception while running year 2094:
    ERROR:* Program exception: msg:  	Assertion failed: timestep must equal 1
    ERROR:func: 	run
    ERROR:file: 	oh_component.cpp
    ERROR:ffile:	oh_component.cpp
    ERROR:
    ERROR:line: 	144
    ERROR:
    Model run completed.

(few changes is made in xml input.)

**Comment by glacierRing** [comment]
What's more, I ran the batch_SSP_REF.xml, and I found SSP5 baseline scenario cannot reach 8.5W/m2 in 2100, is that a acceptable result?  SSP1 baseline scenario cannot reach 6.0W/m2 in 2100 while I found policy_target_6p0_spa1.xml in policy files, I am quite confused about it.
Quite a number of problems °(°ˊДˋ°) °

**Comment by glacierRing** [comment]
I ran the batch_SSP_SPA.xmls in GCAMv5.2, all ran successfully. I cannot find any reason which led to different results between two versions.  
@kvcalvin I have tried the configuration_policy.xml,  It turned out that its not an effective solution to my issue: as there are target_finder files and tax files(carbon_tax_0.xml) in batch_SSP_SPA.xml. Would you mind giving me some advice please?

**Comment by glacierRing** [comment]
**I got the same error in GCAMv5.2 !**  The target_finder_log shows model tried different taxes which decreases from 5 to 0 and eventually -nan value was taken as trial, which lead to this error( invalid price generated by solver) 
It got 4.49638 W/m2 while 4.5 as target, how to set a larger tolerance for it. It seems that target-tolerance value in forcing_target_4p5.xml doesn't work.

**Comment by panday1995** [comment]
Hi @glacierRing, did you solve the issue? I also meet the same issue when running batch_SSP_SPA23.xml in GCAM5.2, but ssp1 and ssp4 goes correctly.

**Comment by glacierRing** [comment]
You can try to change the initial tax guess in xml files. But this method cannot solve all my problems, I am still looking for other ways.
Can you post your target-finder-log files? @panday1995

**Comment by panday1995** [comment]
@glacierRing, 
[target_finder_log.txt](https://github.com/JGCRI/gcam-core/files/5682458/target_finder_log.txt)

I've already set my initial tax guess of 90 for ssp2-RCP-2.7 and 120 for ssp2-RCP-1.9. Looks like, even though some error popped up, the results were anyway exported to database. So far I got the results for ssp2-RCP-2.7. The forcing in the results in 2100 is 2.6 W/cm2. So, seems good. But for ssp2-RCP-1.9, these errors kept popping up in every iteration (The iteration is still going on). So I am worrying those ERRORs matter or not (will it finally cause calculation fail or something).

**Comment by glacierRing** [comment]
Yes, you can get the output even the model is not solved correctly. But I think the output cannot be viewed as a valid result.  
I found no error nor nan value in your log.  @panday1995 ???

**Comment by glacierRing** [comment]
Is there any problem when you constrain rcp4.5 in ssp3? I tried to set the initial tax while the model solves the forcing target in different periods (2090, 2095, 2100), i cannot control the tax used in next periods.  @panday1995  do you have any idea?
![image](https://user-images.githubusercontent.com/63778255/101975309-82036480-3c76-11eb-9e53-649198dc5456.png)

**Comment by panday1995** [comment]
I calculated only RCP-2.6 and RCP-1.9. Have no idea of How would RCP-4.5 goes. But look at your log, seems in 2088  the target has already finished (The default target tolerance is 1%). So my guess is that maybe because the forcing target has reached, so no need to continue calculation for the subsequent periods.

**Comment by panday1995** [comment]
> Yes, you can get the output even the model is not solved correctly. But I think the output cannot be viewed as a valid result.
> I found no error nor nan value in your log. @panday1995 ???

Sorry, but how can I know if my model is solved correctly or not? I thought the only criteria is to examine if a policy target is reach.

**Comment by glacierRing** [comment]
I replaced default secanter method with the bisector method in target finder. Nan value may be avoided in this way. @panday1995

**Comment by github-wbx** [comment]
@glacierRing  Hi! As mentioned above, you have run the batch_SSP_SPA.xmls in GCAMv5.2 successfully, I also try to run the batch_SSP_SPA.xml in GCAMv5.2, but failed. So could you tell me which configuration file you have used, configuration_ref, configuration_policy or others, and I would be very grateful if you post  your  configuration.xml file.

**Comment by glacierRing** [comment]
Actually, I used the configuration_ssp.xml and replaced the default batch file&nbsp;with&nbsp;batch_SSP_SPA.xml files.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "github-wbx"<notifications@github.com&gt;; 
发送时间: 2020年12月21日(星期一) 中午11:32
收件人: "JGCRI/gcam-core"<gcam-core@noreply.github.com&gt;; 
抄送: "sunyixin"<893518622@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [JGCRI/gcam-core] batch_SSP_SPA.xml running problems in GCAMv5.3 (#125)





 
@glacierRing  Hi! As mentioned above, you have run the batch_SSP_SPA.xmls in GCAMv5.2 successfully, I also try to run the batch_SSP_SPA.xml in GCAMv5.2, but failed. So could you tell me which configuration file you have used, configuration_ref, configuration_policy or others, and I would be very grateful if you post  your  configuration.xml file.

**Comment by github-wbx** [comment]
@glacierRing  Thank you for your reply.  Is that right as belows, just change the BatchFileName in configuration_ssp_xml, and customize a scenario name.

<?xml version="1.0" encoding="UTF-8"?>
-<Configuration>
-<Files>
<Value name="xmlInputFileName">../input/gcamdata/xml/modeltime.xml</Value>
**<Value name="BatchFileName">batch_SSP_SPA2.xml</Value>**
<Value name="policy-target-file">../input/policy/forcing_target_4p5.xml</Value>
<Value name="GHGInputFileName">../input/magicc/inputs/input_gases.emk</Value>
<Value name="xmldb-location" append-scenario-name="0" write-output="1">../output/database_basexdb</Value>
<Value name="restart" append-scenario-name="0" write-output="1">./restart/restart</Value>
<Value name="xmlDebugFileName" append-scenario-name="1" write-output="1">debug.xml</Value>
<Value name="climatFileName" append-scenario-name="0" write-output="1">gas.emk</Value>
<Value name="costCurvesOutputFileName" append-scenario-name="1" write-output="1">cost_curves.xml</Value>
<Value name="batchCSVOutputFile" append-scenario-name="0" write-output="1">batch-csv-out.csv</Value>
<Value name="supplyDemandOutputFileName" append-scenario-name="0" write-output="0">SDCurves.csv</Value>
<Value name="flow-graph" append-scenario-name="0" write-output="0">gcam-flow-graph.dot</Value>
<Value name="dependencyGraphName" append-scenario-name="0" write-output="0">DependencyGraph.dot</Value>
<Value name="landAllocatorGraphName" append-scenario-name="0" write-output="0">LandAllocatorGraph.dot</Value>
</Files>
<ScenarioComponents> </ScenarioComponents>
-<Strings>
****
<Value name="debug-region">USA</Value>
<Value name="MAGICC-input-dir">../input/magicc/inputs</Value>
<Value name="MAGICC-output-dir">../output</Value>
<Value name="AbatedGasForCostCurves">CO2</Value>
</Strings>
-<Bools>
<Value name="CalibrationActive">1</Value>
<Value name="BatchMode">1</Value>
<Value name="find-path">0</Value>
<Value name="createCostCurve">0</Value>
<Value name="debugChecking">0</Value>
<Value name="simulActive">1</Value>
<Value name="PrintValuesOnGraphs">1</Value>
<Value name="ShowNullPaths">0</Value>
<Value name="PrintPrices">1</Value>
</Bools>
-<Ints>
<Value name="numMarketsToFindSD">10</Value>
<Value name="numPointsForSD">21</Value>
<Value name="numPointsForCO2CostCurve">5</Value>
<Value name="carbon-output-start-year">1705</Value>
<Value name="climateOutputInterval">5</Value>
<Value name="parallel-grain-size">50</Value>
<Value name="stop-period">-1</Value>
<Value name="stop-year">-1</Value>
<Value name="restart-period">-1</Value>
<Value name="restart-year">-1</Value>
</Ints>
<Doubles> </Doubles>
</Configuration>

**Comment by github-wbx** [comment]
@glacierRing  Thank you for your reply. Another question I want to ask is the Github just released the Source code GCAM v5.3, not included the Package GCAM v5.3, so where you download the Package GCAM v5.3 or how can I obtain/generate the Package GCAM v5.3.

**Comment by nbn14** [comment]
Hi @glacierRing and @panday1995, 
I am trying to reproduce the 1.5 degree scenario with GCAM. The literature mentioned I can get to this with SSP-SPA1,2 and 5 and RCP1.9. I have tried to run GCAM5.2 using configuration_ssp.xml and batch_SSP_SPA1(23 and 5) inserted into the config file. I am assuming I would also need to set the policy target field to policy_target_1p9_sp1(23 and 5) in the config file. However, I got to 4.6 instead of 1.9 Wm-2. Has anyone managed to reproduce the 1.5 degree scenario from GCAM5.2 or any other GCAM version?

**Comment by kvcalvin** [comment]
A few answers:
1. You should use `configuration_ssp.xml` when running the `batch_SSP_*` files. 
2. The GCAM SSP5 does not reach 8.5 W/m2. This was true with the original SSPs and is still true. The SSPs were defined around storylines and the implementation of the SSP5 storyline in GCAM does not result in 8.5 W/m2. 
3. I have included more information on the 1.9 W/m2 scenario in https://github.com/JGCRI/gcam-core/issues/134

If I missed any of the questions in this thread, could you please open a new issue with that question only? It is easier for us if issues/questions are separated.
