### ISSUE TITLE
GCAM 5.1.3: Where to add 'carbon_tax_0.xml' in Target finder mode?

### ISSUE THREAD

**Issue by panday1995** [JGCRI/gcam-core#126]
Hi, I'm trying to reproduce SSPs with policy target `forcing_target_3p7.xml` and `forcing_target_2p6_overshoot.xml` in **Batch mode** using GCAM v5.1.3 (v5.2 and v5.3 turned out to have a bunch of bugs so I abondoned).

The [official doc](http://jgcri.github.io/gcam-doc/v5.1/user-guide.html#315-ints-input-options) indicates that 

_when a user is running target finder with a negative emissions budget constraint they should be sure to set up the market, for example by reading in the policy file **carbon_tax_0.xml**._

Here, I'm confused where to read in the policy file. I tried to add the file into the `batch_SSP_REF.xml` file. So now, my batch scenario file is like this 
[batch_SSP_REF.txt](https://github.com/JGCRI/gcam-core/files/5649947/batch_SSP_REF.txt)

My configuation file is like this [configuration.txt](https://github.com/JGCRI/gcam-core/files/5649915/configuration.txt)

I tried running it. Actually, everything works well, but just the calculation took too much time, e.g. eight hours have passed, the first scenario (SSP4 with forcing target 3.7) has not yet been solved. **Is this reasonable? How can I make the calculation faster? should I put the _carbon_tax_0.xml_ file in the policy target runner section?**

Thanks a lot!

**Comment by panday1995** [comment]
The calculation ended with 
```
Error setting price in marketplace for: CO2, value: -nan(ind)
ERROR:Exiting target finding search as the iterations limit was reached.
```

**Comment by panday1995** [comment]
Problem solved with putting carbon_tax_0.xml in the ComponentsSet of the batch_SSP_REF.xml

**Comment by pramishp** [comment]
@panday1995 , Can you please provide the configuration that worked for you ?
