### ISSUE TITLE
Where can I download GCAM-China and its user's guide ?

### ISSUE THREAD

**Issue by LinchongOu** [JGCRI/gcam-core#129]

**Comment by xiaoxiao-maggie** [comment]
I also want to get that!

**Comment by sypnl** [comment]
We don't have it available right now but will sometime in the future.

**Comment by wahmed7** [comment]
GCAM-China is available now?

**Comment by sypnl** [comment]
GCAM-China will not be available in 2022.

**Comment by JDoBai** [comment]
老师， 请问GCAM-China是否即将上线？很期待能通过GCAM-China获取到SSPs路径下未来各省的能源需求量 : )

**Comment by heishanmao** [comment]
How about in 2024？

**Comment by qinqin66** [comment]
![image](https://github.com/JGCRI/gcam-core/assets/55978115/765ce5cc-97bc-4bf3-9475-890c5aa1574d)

**Comment by ouyang363** [comment]
https://github.com/umd-cgs/gcam-china
