### ISSUE TITLE
XML files generated by GCAM v5.3 source code and ran in GCAM v5.2 Package

### ISSUE THREAD

**Issue by github-wbx** [JGCRI/gcam-core#131]
@rjplevin  Hi! 
The Github released the GCAM v5.3 source code, and not included GCAM v5.3 package, so I just generated the XML input files by GCAM v5.3 source code, and ran in GCAM v5.2 package. But it did not work, the log file as belows. Thank you for any advice.
[log file.txt](https://github.com/JGCRI/gcam-core/files/5727683/log.file.txt)

**Comment by kvcalvin** [comment]
GCAM input files are version specific. Some files may work in older versions but others will not.
