### ISSUE TITLE
Questions about GCAM

### ISSUE THREAD

**Issue by heishanmao** [JGCRI/gcam-core#132]
Hello，

I am a Ph.D. student and interested in The GCAM project to connect my research about crop production.

I already built and run GCAM 5.3 and found it is a so big and complex system. It is a little bit hard for me to totally understand the whole project.

In other words, Could anyone give me some recommendations on where to find the detailed text description about how the GCAM system to predict crop production?

I am pretty would like to know the detailed input and output variables, parameters to predict ag crop production. It means what kind of data GCAM used to calculate the crop production and how to use them. Especially, if you can provide some equation about this whole process or where I can find them that is also good.

Thank you very much.

**Comment by kvcalvin** [comment]
There is information on how GCAM's agriculture and land use system works in our online documentation: http://jgcri.github.io/gcam-doc/aglu.html. In addition, the equations are documented in this paper: https://www.worldscientific.com/doi/abs/10.1142/S2010007814500031. A list of inputs and outputs can be found in: https://gmd.copernicus.org/articles/12/677/2019/
