### ISSUE TITLE
GCAM RCP_1p9

### ISSUE THREAD

**Issue by pengy14** [JGCRI/gcam-core#134]
I want to use GCAM to simulate the CO2 pathway under 1.5 degree in China. So, I modified the configuration.xml file and only change the following attribute:
```<Value name="policy-target-file">../input/policy/policy_target_1p9_spa1.xml</Value>```
 After that, I run GCAM and query the result. I get the emissions below:
![image](https://user-images.githubusercontent.com/14346662/104030739-ce56ab80-5206-11eb-87e0-fb2257173e01.png)

Is this correct to get the emissions under 1.5 degree? I found it higher than I expected. Anyone can help?

**Comment by pengy14** [comment]
Should I change other attributes to simulate 1.5 degree scenario?

**Comment by nbn14** [comment]
Hi @pengy14,

I am also trying to reproduce this 1.5 scenario. Any luck from your end?

**Comment by huanq1** [comment]
> Should I change other attributes to simulate 1.5 degree scenario?

I tried, and got the same result. Have you solve the problem？

**Comment by pengy14** [comment]
I failed and I changed to another method. I guess you can apply your own
data to GCAM instead of using the original, however, I hadn't figure out
where can I input my data.😞

huanq1 <notifications@github.com> 于2021年1月27日周三 下午10:15写道：

**Comment by nbn14** [comment]
I think by running the default GCAM input files and policies, we all get pretty broad curves as you showed above even at the global level for ssp1 1p9. I have not been able to get a steep decrease after 2020 as shown in the literature. I have found that the model does solve for the case of high fixed tax in 2025 like $150 starting. The forcing goes down way below 1.9 in that case, although it seems the runs were successful. Yah unfortunately, I have not succeeded in reproducing the literature sharp decrease with target finder mode...Maybe the negative emission budgets need to be changed or something...

**Comment by kvcalvin** [comment]
All,

`policy_target_1p9_spa1.xml` is different than other GCAM Input files. It cannot be added in the `ScenarioComponents` portion of the configuration file. Instead, it should be included as a `<Value name="policy-target-file">` and activated by setting `find-path` to 1. I recommend starting with the `configuration_policy.xml` file to ensure the correct linking files are included.

As for reproducing the original ssp1-1p9, there have been many changes to GCAM between v4.2 and v5.3, including the addition of water constraints, adding a negative emissions budget, updating the final base year to 2015, and a variety of changes to technology and trade assumptions. I would not expect the model to exactly reproduce previous results. There is some information on differences between GCAMv4.2 and GCAMv5.1 results included in this paper: https://gmd.copernicus.org/articles/12/677/2019/
