### ISSUE TITLE
output

### ISSUE THREAD

**Issue by huanglin6385** [JGCRI/gcam-core#137]
When I run GCAM successful, in output folder, there exists file output/output.xml and folder output/databasex/**.basex.
My question is that are they saving the same information? one is in database, another is in XML?

**Comment by kvcalvin** [comment]
Hi @huanglin6385, 

These files are not the same. `output.xml` consolidates all of the input files. `output/databasex/**.basex` includes the results from the model. Note that in more recent versions of GCAM we have removed `output.xml` because it was confusing and rarely used.
