### ISSUE TITLE
HOW to analyse basex files

### ISSUE THREAD

**Issue by sanshuiii** [JGCRI/gcam-core#138]
After I run GCAM programs, there are basex files generated under the path ./output/database_basexdb. I wonder how can I analyse these files so that i can get the info i need automatically. Is there any toolkits but for ModelInterface(GUI is unnecessary)? Thanks!

**Comment by robbieorvis** [comment]
@rplevin’s pygcam tool is great for this. You can create custom queries and run the queries on the datasets to produce .csv files.

**Comment by ssmithClimate** [comment]
Also rgcam(https://github.com/JGCRI/rgcam)

**Comment by sanshuiii** [comment]
thanks, it helps
