### ISSUE TITLE
Error on make for GCAM-USA data system due to case-sensitivity 

### ISSUE THREAD

**Issue by michaeljaywalsh** [JGCRI/gcam-core#14]
When running make (Ububtu 16.04) in 
`gcam-core/input/gcam-data-system/gcam-usa-data
`
make runs into an error when processing : 
`gcam-core/input/gcam-data-system/gcam-usa-processing-code/level2/L226.en_distribution_USA.R
`
line 27 of this file reads:
`sourcedata( "GCAMUSA_ASSUMPTIONS", "A_gcamusa_data", extension = ".R" )`

while the source data file is listed as `A_GCAMUSA_data.R` which is consistent with what is referenced in all other processing r scripts 

https://github.com/JGCRI/gcam-core/search?p=3&q=A_GCAMUSA_data.R&utf8=%E2%9C%93

**Comment by rplzzz** [comment]
This should be taken care of in our revamp of the data system, which should be coming out (we hope) in the next few months.
