### ISSUE TITLE
Question about inclusion of LUC emissions in global emissions output

### ISSUE THREAD

**Issue by nbn14** [JGCRI/gcam-core#143]
Hello,

I have been using the queries file that came with gcam_reader to read output into pandas dataframe. To get to total net global CO2 or GHG emissions I have been looking at "Co2 emissions by region". It seems that "LUC emissions by region" is tracked separately in GCAM, however it does not seem obvious to me whether LUC emissions has already been incorporated into "Co2 emissions by region". Perhaps I need to sum them to get total global / regional emissions value? Really appreciate it if someone can help please!

Thank you

**Comment by kvcalvin** [comment]
"CO2 emissions by region" only includes fossil fuel & industrial CO2 emissions. You will need to add "LUC emissions by region" to get total CO2 emissions.
