### ISSUE TITLE
New user trying to find the “AWS-gcam-training.pem” file

### ISSUE THREAD

**Issue by almareyna1** [JGCRI/gcam-core#147]
I am a new user, and I am trying to find the  file “AWS-gcam-training.pem” to include in the folder “.ssh”. However, i have followed the step by step instructions and dont know and cannot find the file. 

Any help is greatly appreciate it since it is my first time trying this model.

Alma

**Comment by pralitp** [comment]
Sorry for the confusion.  We had provided those AWS instances during the in person training at the annual GCAM meetings only.
