### ISSUE TITLE
error when having a test run using GCAM4.3

### ISSUE THREAD

**Issue by chenhan1989** [JGCRI/gcam-core#15]
hello, I am new user of GCAM4.3. After downloading all materials provided by the https://github.com/JGCRI/gcam-core/releases , I came across problems like this:
error occurred during initialization of vm unable to load native library: can't find dependent libraries.

Btw, I am quite sure that the JAVA running environment and path setting  are right. 
Could you please help me? Has anyone ever encountered problem like this?

**Comment by rplzzz** [comment]
Can you supply some additional information?  Let's start with, what platform are you trying to run on (linux, mac, windows)?

**Comment by chenhan1989** [comment]
Thanks for your reply! Sure, I am working on windows and the problem is present like this in the picture attached.


发自网易邮箱大师
On 04/28/2017 01:10, Robert Link wrote:

Can you supply some additional information? Let's start with, what platform are you trying to run on (linux, mac, windows)?

**Comment by rplzzz** [comment]
@chenhan1989 I don't see the screenshot you referred to.

**Comment by HaopengGeng** [comment]
> hello, I am new user of GCAM4.3. After downloading all materials provided by the https://github.com/JGCRI/gcam-core/releases , I came across problems like this:
> error occurred during initialization of vm unable to load native library: can't find dependent libraries.
> 
> Btw, I am quite sure that the JAVA running environment and path setting are right.
> Could you please help me? Has anyone ever encountered problem like this?

I encountered the same problem with you, have you solved the problem yet? Could you please help me with the problem ?
