### ISSUE TITLE
Model Interface error

### ISSUE THREAD

**Issue by ssriram1992** [JGCRI/gcam-core#17]
Hi Pralit,

I am trying to run model interface in Window. Somehow when I run the ModelInterface.bat , it gives error. So I got hold of ModelInterface.jar, the executable file and ran it. The application opens. But when I open the database, I don't see any default query. Attempting to create a query gives Java Nullpoint Exception.

Can you help?

Thanks,
Sriram

**Comment by pkyle** [comment]
Hi Sriram,
It sounds like your model_interface.properties file isn't pointing to a query file. That should be located in the same folder as ModelInterface.jar, and should point to the Main_queries.xml file that is usually located in the output/queries folder. The appropriate line typically looks like this:
<entry key="queryFile">../output/queries/Main_queries.xml</entry>
Page
