### ISSUE TITLE
Clarification on carbon tax values in policy file example

### ISSUE THREAD

**Issue by agobba** [JGCRI/gcam-core#176]
I'm implementing a carbon price constraint via a policy file as specified under https://jgcri.github.io/gcam-doc/policies_examples.html#carbon-price. I'm unsure about what the carbon price represents in real-life terms. 

If I implement a carbon price of $1/tC (in $1990) in the USA, is that directly equivalent to a policymaker in the US attaching a $ tax/price to each ton of carbon (adjusted for inflation)? or does the $1/tC specified in GCAM include other intangible costs such as social or environment costs, and hence cannot be directly mapped to a real-life carbon tax policy?

**Comment by ssmithClimate** [comment]
Carbon taxes in GCAM place a direct economic cost on the fossil fuel. So they map directly to prices consumers and producers would see.

**Comment by agobba** [comment]
Thank you!

**Comment by n789123** [comment]
Hello, I would like to ask in which xml your carbon price constraint is modified

**Comment by pkyle** [comment]
Please see the `input/policy/carbon_tax/*.xml` files
I don't see any constraint files in the release package, but they follow the same pattern in the XML. For example,
```
            <policy-portfolio-standard name="CO2">
                <policyType>tax</policyType>
                <min-price fillout="1" year="2025">1.0</min-price>
                <market>USA</market>
                <constraint year="2025">1329.53</constraint>
```
Where the constraint values are indicated in Mt C per year (i.e., not CO2).
