### ISSUE TITLE
The energy consumption in the model interface of the base year (2015) is inconsistent with the energy consumption in the IEA

### ISSUE THREAD

**Issue by stm19950929** [JGCRI/gcam-core#182]
Taking the energy consumption of China's industry in 2015 as an example, the data of modelinterface is 58.756EJ, the data of IEA is 42.74EJ, and the data of base-service in industry.xml is 49EJ. I want to know what caused the difference between these?

**Comment by pkyle** [comment]
The apparent IEA/GCAM difference here is just definitional, i.e. which of IEA's sectors ("flows") get assigned to GCAM's industrial sector. The TOTIND flow (which corresponds with the `in_industry_general` sector below) is only a part of all of the different sources of energy in GCAM's industrial sector, which also includes a bunch of processes considered part of the energy transformation sector in the IEA data. For example blast furnaces are part of the transformation sector in the IEA data but are considered part of the industrial sector in GCAM. The mapping from IEA's flows to GCAM's intermediate sectors can be found in `input/gcamdata/inst/extdata/energy/mappings/IEA_flow_sector.csv`. Here are the quantities of energy that get added up for each of these intermediate sectors, in the China region in 2015:
| sector                               | tfe   |
| ------------------------------------ | ----- |
| in\_industry\_agriculture            | 1.69  |
| in\_industry\_chp                    | 0.00  |
| in\_industry\_ctl                    | 0.15  |
| in\_industry\_energy distribution    | 0.08  |
| in\_industry\_feedstocks             | 6.62  |
| in\_industry\_general                | 42.68 |
| in\_industry\_gtl                    | 0.00  |
| in\_industry\_ownuse                 | 0.32  |
| in\_industry\_pipeline               | 0.00  |
| net\_industry\_energy transformation | 10.16 |
| net\_industry\_oil refining          | 0.38  |
As for the difference between energy consumption and base-service, I wouldn't advise reading too much into that. Service = energy * efficiency, and the efficiencies are not especially meaningful in the industrial sector.

**Comment by stm19950929** [comment]
> The apparent IEA/GCAM difference here is just definitional, i.e. which of IEA's sectors ("flows") get assigned to GCAM's industrial sector. The TOTIND flow (which corresponds with the `in_industry_general` sector below) is only a part of all of the different sources of energy in GCAM's industrial sector, which also includes a bunch of processes considered part of the energy transformation sector in the IEA data. For example blast furnaces are part of the transformation sector in the IEA data but are considered part of the industrial sector in GCAM. The mapping from IEA's flows to GCAM's intermediate sectors can be found in `input/gcamdata/inst/extdata/energy/mappings/IEA_flow_sector.csv`. Here are the quantities of energy that get added up for each of these intermediate sectors, in the China region in 2015:
> 
> sector	tfe
> in_industry_agriculture	1.69
> in_industry_chp	0.00
> in_industry_ctl	0.15
> in_industry_energy distribution	0.08
> in_industry_feedstocks	6.62
> in_industry_general	42.68
> in_industry_gtl	0.00
> in_industry_ownuse	0.32
> in_industry_pipeline	0.00
> net_industry_energy transformation	10.16
> net_industry_oil refining	0.38
> As for the difference between energy consumption and base-service, I wouldn't advise reading too much into that. Service = energy * efficiency, and the efficiencies are not especially meaningful in the industrial sector.

Thank you very, very, very much for your answers to me. The understanding of these concepts can help me speed up my next research work.

**Comment by stm19950929** [comment]
> The apparent IEA/GCAM difference here is just definitional, i.e. which of IEA's sectors ("flows") get assigned to GCAM's industrial sector. The TOTIND flow (which corresponds with the `in_industry_general` sector below) is only a part of all of the different sources of energy in GCAM's industrial sector, which also includes a bunch of processes considered part of the energy transformation sector in the IEA data. For example blast furnaces are part of the transformation sector in the IEA data but are considered part of the industrial sector in GCAM. The mapping from IEA's flows to GCAM's intermediate sectors can be found in `input/gcamdata/inst/extdata/energy/mappings/IEA_flow_sector.csv`. Here are the quantities of energy that get added up for each of these intermediate sectors, in the China region in 2015:
> 
> sector	tfe
> in_industry_agriculture	1.69
> in_industry_chp	0.00
> in_industry_ctl	0.15
> in_industry_energy distribution	0.08
> in_industry_feedstocks	6.62
> in_industry_general	42.68
> in_industry_gtl	0.00
> in_industry_ownuse	0.32
> in_industry_pipeline	0.00
> net_industry_energy transformation	10.16
> net_industry_oil refining	0.38
> As for the difference between energy consumption and base-service, I wouldn't advise reading too much into that. Service = energy * efficiency, and the efficiencies are not especially meaningful in the industrial sector.

Thank you very, very, very much for your answers to me. The understanding of these concepts can help me speed up my next research work.
