### ISSUE TITLE
GIS file for 384 Land regions and 235 Water Basins

### ISSUE THREAD

**Issue by rubcalvo** [JGCRI/gcam-core#198]
Hi! Is there a file (Shapefile, Netcdf, Geotiff) for the 384 Land regions and 235 Water Basins? I have been looking in various folders of GCAM core and also in other projects (Demeter, Moirai, Persephone, GCAM Data), but found nothing easily accesible. 

Thanks!

**Comment by kanishkan91** [comment]
Hi . Minted, citable versions of rasters, shapefiles and other files are available here -https://zenodo.org/record/4688451#.YiKITOjMJaQ

Please do let me know if this works for you.

**Comment by rubcalvo** [comment]
Great! Thank you so much!
