### ISSUE TITLE
Severe Error at the end of Reference run, Failed to find XMLDBDriver

### ISSUE THREAD

**Issue by djtrainwreckx** [JGCRI/gcam-core#2]
<img width="800" alt="severe error - failed to find java class xmldbdriver to write to the xml database" src="https://cloud.githubusercontent.com/assets/15677829/19365408/94be8db8-9160-11e6-8680-c6d2f2dc535b.png">

Setup GCAM 4.3 by unpacking Core GCAM, Data System and Windows binaries individually, copied 'input' folder and all of files/folders under windows binaries into Core's main directory. Configuration_ref file copied and renamed configuration. Hit 'run gcam' file.

-Osman

**Comment by pralitp** [comment]
Judging from the warning message produced by first thought is there is something about the space in the "GCAM 4.3" that is causing trouble.  You will notice in the message there it was represented by "%20".  Sometimes this is the right way to represent the space but other times it isn't.

Could you try to replace the space with an underscore and see if that works?

On thing you could do to speed up the process of debugging this is in `configuration.xml`  you will notice at the very end `<Value name="stop-period">-1</Value>`.  You can change `-1` to `2`, for instance, to only run the first two periods before writing the results to the database.

**Comment by djtrainwreckx** [comment]
will do

**Comment by djtrainwreckx** [comment]
Problem resolved. Scary warning, dumb cause. Thanks
-Osman

**Comment by pralitp** [comment]
No worries, I will look into making it resilient to spaces.

**Comment by rplzzz** [comment]
Fixed in 48cbb97
