### ISSUE TITLE
Model did not solve within the set iterations

### ISSUE THREAD

**Issue by rsajedi** [JGCRI/gcam-core#20]
I'm trying to replicate a GCAM 3 Model simulation in the new GCAM 4.3 . I ran the model in target finder mode to limit radiative forcing to 3.7W/m2. Model starts correctly in the beginning (results for the first years also are close enough to the original results, considering changes in the model, but diverges at some point) but in dispatch no. 18 it starts to generate an error that says model did not solve within the set iterations, I have tried to change the maximum iterations in \policy\forcing_target_3p7.xml from 100 to 500 but to no avail. Is this the correct place to set the maximum iterations and do you have any thoughts on the source of this error if changing the maximum iterations is not a good approach? 

Thanks,
Reza

**Comment by michaeljaywalsh** [comment]
Reza, 
Could you post the gcam-core\exe\logs\main_log.txt file? I think I can help but it would be easier to know what exactly the errors are.

**Comment by rsajedi** [comment]
Thanks Michael for your reply, I have attached the log file. Actually I did not make significant changes in the model, the whole changes from a demo run (which was done without any problem) are:

-running the Uniform Carbon Tax (UCT) scenario.
-running in target finder mode with 3.7W/m2 ceiling.

Thanks,
Reza

[main_log.txt](https://github.com/JGCRI/gcam-core/files/1168504/main_log.txt)

**Comment by michaeljaywalsh** [comment]
So there are several levels of iterations that occur within a target finder run. The highest is the one that seeks to find a specified target (and trajectory) by varying a parameter such as the carbon price. This iterator runs a full series of periods over and over to achieve a certain goal (e.g. 3.7) while varying a certain parameter (carbon price). The number of iterations for this is set in the target finder policy file. Each iteration is labeled by the the Dispatch number. Your log shows that the run got out to dispatch 30, so increasing `max-iterations` will have no impact.

The `did not solve` failure notice is actually occurring while GCAM is solving a single period within a single dispatch trial of carbon prices. In this case the solver iterator is maxing out at ~2500 iterations 
note: `ERROR:Model did not solve period 17 within set iteration 2514`

You can extend this by increasing the `max-model-calcs` parameter from 2500 to a number that you are willing to tolerate in the /input/solution/cal_broyden_config.xml file. 

It does look like the target finder did succeed `(Model exiting successfully`), but with a single period failing. I'm sure others can better explain why this happened, but it doesn't look like it is that far off, so a couple more iterations on the solver side might help you get to a solution.
