### ISSUE TITLE
How to shut down CCS in scenarios?

### ISSUE THREAD

**Issue by Cermouth** [JGCRI/gcam-core#206]
I wanted to shut down CCS use in electricity generation in some scenarios so I changed the share-weight (from 1 to 0) in the electricity.xml file. But I found that in the original configuration.xml file (GCAM v5.4), the row of reading electricity.xml was commented: 

So I think this means that the changes I made in the electricity.xml file cannot be imported into the model. I uncommented this row and run the model but there just come many unsolved errors. Maybe the model just uses electricity data from other locations? Then how can I model scenarios where no CCS allowed in power sector?

**Comment by danli450** [comment]
i also have this problem. DO you solved it now?

**Comment by debibooo** [comment]
Hi, could you tell me the steps to shut down the CCS in the electricity sector? thanks.

**Comment by pkyle** [comment]
If you only want to shut off CCS technologies in the power sector, you can set their long-term share-weights to zero in `inst/extdata/energy/A23.globaltech_shrwt.csv` and then re-build the XML file. Just the rows where the string CCS is in the technology name. Note that other CCS technologies e.g. in the refining and hydrogen sectors will still be available.
