### ISSUE TITLE
GCAM v3.0

### ISSUE THREAD

**Issue by rsajedi** [JGCRI/gcam-core#22]
Hi, 

I'm trying to run GCAM 3.0 but I was only successful in finding "gcam-core-3.0" online. Could you please advise on how can I find other parts, required for running the model?

Thanks,
Reza

**Comment by rplzzz** [comment]
The GCAM 3.0 release is available from the releases page:  

https://github.com/JGCRI/gcam-core/releases

It should contain everything you need to build the model from source, as well as all of the input data.  We do not offer pre-built binary packages for older versions of the model, so compiling from source is your only option for running these versions.
