### ISSUE TITLE
Problem with GCAM Data System in v6.0

### ISSUE THREAD

**Issue by rubcalvo** [JGCRI/gcam-core#225]
Dear all, 
I've been trying the new version of GCAM and I've encountered a problem when using GCAM Data System to create a new scenario. Specifically, changing the groundwater availability to 05pct in constant.R
When I try to run the driver (both driver_drake() and driver()) i get the following error:

```
GCAM Data System v5.1
Found 424 chunks
Found 4324 chunk data requirements
Found 2461 chunk data products
Error in driver() : 
  Outputs appear multiple times: L113.ag_bioYield_GJm2_R_GLUL232.Supplysector_indL232.SubsectorLogit_indL232.FinalEnergyKeyword_indL232.SubsectorShrwtFllt_indL232.SubsectorInterp_indL232.StubTech_indL232.GlobalTechShrwt_indL232.StubTechInterp_indL232.GlobalTechEff_indL232.GlobalTechCoef_indL232.GlobalTechCost_indL232.GlobalTechSecOut_indL232.GlobalTechCSeq_indL232.StubTechCalInput_indenergyL232.StubTechCalInput_indfeedL232.StubTechProd_industryL232.StubTechCoef_industryL232.FuelPrefElast_indenergyL232.PerCapitaBased_indL232.PriceElasticity_indL232.BaseService_indL232.IncomeElasticity_ind_gcam3L232.IncomeElasticity_ind_gssp1L232.IncomeElasticity_ind_gssp2L232.IncomeElasticity_ind_gssp3L232.IncomeElasticity_ind_gssp4L232.IncomeElasticity_ind_gssp5L232.IncomeElasticity_ind_ssp1L232.IncomeElasticity_ind_ssp2L232.IncomeElasticity_ind_ssp3L232.IncomeElasticity_ind_ssp4L232.IncomeElasticity_ind_ssp5
```

**Comment by russellhz** [comment]
@rubcalvo I wasn't able to recreate this error on my system. Are you able to build the data system without this change to constants.R? One note is that my gcamdata only finds 420 chunks - I wonder if somehow old chunks are in your new GCAM data system.

**Comment by rubcalvo** [comment]
@russellhz thanks! I think that was the problem, because I downloaded gcamdata folder again from the repo and it works now.
