### ISSUE TITLE
Issue with keeping carbon tax fixed

### ISSUE THREAD

**Issue by msispah** [JGCRI/gcam-core#238]
Hi everyone, I want to keep carbon prices fixed through out the GCAM run and then see how much global mean temperature will reach by 2100. I have used 'fixed tax' in the carbon_tax_25_5.xml. However, carbon prices keep changing always to reach the forcing target. I even tried without forcing target but that resulted in error. Can anyone please suggest what other parameters need to be fixed so that carbon prices do not change during the run? Thank you in advance!

**Comment by mbins** [comment]
Can you please share the configuration file you used?  It sounds like the model is still operating in target finder mode - it will be easier to diagnose why with the configuration file.

**Comment by msispah** [comment]
Hi @mbins, I am using the policy configuration file. I do not know how to turn off the target finder mode. If I remove this, GCAM gives error while running. As GitHub does not allow .xml file, I am attaching the .txt for configuration file.
[configuration.txt](https://github.com/JGCRI/gcam-core/files/9650729/configuration.txt)

Thank you so much for the help.

**Comment by mbins** [comment]
Thanks @msispah!  In your configuration file, this bool is set to 1:

<Value name="find-path">1</Value>

That tells GCAM to run in target finder model.  If you simply change the value to 0, it should run with the tax path you've specified.

**Comment by msispah** [comment]
Thank you @mbins! Did you mean find_path bool? Sorry, I cant see that in your comment. I had actually set find_path to zero initially  but then there was no effect of carbon tax on the scenario. I will try it out again if that's the case.

**Comment by mbins** [comment]
Yes I meant the find_path bool.  Sorry, I forgot to put the XML line in a code block and it was deleted.

If setting this to zero doesn't work, I would double check your policy files to ensure that the name of the `ghgpolicy` in your `carbon_longtermtax.xml` and `carbon_neartermtax.xml` files are consistent with the `linked-policy` name in `2025_target_finder_phasein.xml`.
