### ISSUE TITLE
links broken

### ISSUE THREAD

**Issue by amnmalik** [JGCRI/gcam-core#241]
The following link is broken https://www.pnnl.gov/projects/jgcri/models/gcam/gcam-community/

**Comment by amnmalik** [comment]
also https://www.pnnl.gov/projects/jgcri/annual-meetings/

**Comment by mbins** [comment]
Thank you for flagging this issue, @amnmalik.  The annual meetings page is:  https://www.pnnl.gov/projects/jgcri/annual-meeting-resources.  Where did you find the broken link (https://www.pnnl.gov/projects/jgcri/annual-meetings/)?

I'm not sure what info was located at https://www.pnnl.gov/projects/jgcri/models/gcam/gcam-community/, but some of the relevant info may be at:  https://gcims.pnnl.gov/community.
