### ISSUE TITLE
No ModelInterface.jar in the window_binaries package

### ISSUE THREAD

**Issue by yanghaozhe** [JGCRI/gcam-core#25]
I have downloaded the GCAM model from the GitHub.
   However, in the windows_binaries package, there supposed to be ModelInerface.jar in the folder ModelInterface. But I only found run-model-interface.bat and model_interface.properties in the folder. 
   Could you please tell me where to find the ModelInterface.jar?

**Comment by pralitp** [comment]
Since GCAM 4.3 the `ModelInterface.jar` is located in `input/gcam-data-system/_common/ModelInterface/src` and is referenced from there in `run-model-interface.bat`.
