### ISSUE TITLE
How to add new Secondary (Animal) Commodities type?

### ISSUE THREAD

**Issue by Randynat** [JGCRI/gcam-core#28]
Hello, 
I'm new to GCAM and I had a few questions. From what I know, GCAM has 6 categories of meat (beef, dairy, pork, poultry, sheep & goat, and other meat & fish) modeled in. Can I use GCAM to simulate a new type of meat production?  And if so, which file I need to modify to include the new meat type?

**Comment by kvcalvin** [comment]
If you are looking to re-map the existing FAO data to a new set of categories, I'd recommend looking through the data system for anywhere the string "Pork" appears and modifying those files to add your new category.
