### ISSUE TITLE
Help with "GCAM Policy Cost" 

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#29]
Hi everyone
I am currently trying to get GCAM to compute the policy cost of my simulations. 
According to the GCAM tutorial, the way to handle this is to turn on the CO2 cost curve.
I tried running a simulation run the with "createCostCurve" turned on but I got an error message "Could not find string: AbatedGasForCostCurve".  Base this I need help with the following: 
1. How do I create and apply an abate cost curve?
2. Secondly is there another way of computing the cost of a policy? 

Thank you.

**Comment by nancybrett** [comment]
HI
Was this issue every answered, I can not seem to see a answer and I have the same issue.
BR Nancy

**Comment by pkyle** [comment]
This is just a warning message that can be safely ignored.
The default behavior is for GCAM to use "CO2" as the GHG market name, for which cost curves are computed. If you search the `cvs` folder for that string, you'll find the following line in `total_policy_cost_calculator.cpp`:
```
    mGHGName = conf->getString( "AbatedGasForCostCurves", "CO2" );
```
The second argument is the default value used if none is read in to the `Strings` of the configuration file.
