### ISSUE TITLE
Unable to located jvm.dll !!!

### ISSUE THREAD

**Issue by Aubutio** [JGCRI/gcam-core#30]
I use the version4.4GCAM, when i double CLICK the object-main file ,there is a warning like this:Unable to located jvm.dll   
i have already installization one Java ,and delete the REM in the run-gcam file.
i hope any one could help me ,thank you very much.
   
you can contact me :
      e-mail: 15062276093@163.com
      name：Aubutio Z

**Comment by Aubutio** [comment]
ps : i can run the file of "run-gcam" correctly

**Comment by zyqzxn** [comment]
Same issue here. Any suggestions?

**Comment by afrasmile** [comment]
You should install Java SE 7 version, instead of 8 version. You can find the previous version at 
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html

It works for me.
