### ISSUE TITLE
Critical minerals for power sector

### ISSUE THREAD

**Issue by Kofimoley** [JGCRI/gcam-core#304]
Hi everyone, so I was in attendance for the just ended GCAM annual meeting. One of the presentations that really caught my attention was the one on critical minerals for the power sector. I already downloaded GCAM7 but I am yet to see any xml files related to these critical minerals or as a query option at the model interface.
Are there some existing xml files (purposely for these critical minerals) to include as add-ons in the main configuration file that were not included in the release version OR are they existing in csv files which I would have to create the xml files myself using gcamdata through R? 
Finally, if one should get these files included in a scenario run, which query at the model interface would give the results for critical minerals used in the power sector? I would be very grateful to receive some feedbacks. Thank you in advance.

**Comment by hassaniazi** [comment]
Hi, model development related to minerals research is still in progress and has not been included in the v7 release yet. But you can expect the release of a poster presented by Yang Qiu later this month

**Comment by Kofimoley** [comment]
> Hi, model development related to minerals research is still in progress and has not been included in the v7 release yet. But you can expect the release of a poster presented by Yang Qiu later this month

@hassaniazi that's great to hear. Looking forward to it. Thanks a lot.
