### ISSUE TITLE
java.lang.NullPointerException when I try to use ModelInterface 

### ISSUE THREAD

**Issue by Miayuyao** [JGCRI/gcam-core#31]
Hi， 
     Everyone, when I try to use ModlInterface  to see my results,  there is always a Unexpected Error:java.lang.NullPointException. 
    Is there anyone who met the problem before?  I'm urgent to wait for your suggestion!!!!!
    Thank u so much

**Comment by kvcalvin** [comment]
See also https://github.com/JGCRI/gcam-core/issues/34

**Comment by kvcalvin** [comment]
Closing this one as duplicate.
