### ISSUE TITLE
Building GCAM in ubuntu

### ISSUE THREAD

**Issue by john-musau** [JGCRI/gcam-core#33]
I get the following error when building GCAM for ubuntu 16.04
Please advise.

make -C ../../containers/source containers_dir
make[1]: Entering directory '/media/jmwanzia/D/GCAM/gcam_core/cvs/objects/containers/source'
g++ -O2 -ggdb -DNDEBUG -DFUSION_MAX_VECTOR_SIZE=30  -MMD -std=c++14 -Wno-deprecated -I -I -I/linux   -I../../climate/source/hector/headers -I -I../.. -I/home/jmwanzia/include   -DJARS_LIB="\"\"" -DGCAM_PARALLEL_ENABLED=0 -DUSE_LAPACK=0 -DUSE_HECTOR=1   -c -o batch_runner.o batch_runner.cpp
batch_runner.cpp:44:43: fatal error: util/base/include/definitions.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'batch_runner.o' failed
make[1]: *** [batch_runner.o] Error 1
make[1]: Leaving directory '/media/jmwanzia/D/GCAM/gcam_core/cvs/objects/containers/source'
Makefile:38: recipe for target 'containers_dir' failed
make: *** [containers_dir] Error 2

**Comment by rplzzz** [comment]
It looks like the paths to the include files for Boost, Xercesc, and Java are not set up (each one produces a `-I ` in the compiler line.  You can find instructions for configuring the relevant environment variables in the setup guide:
http://jgcri.github.io/gcam-doc/gcam-build.html#41-building-with-makefile

**Comment by ashiklom** [comment]
@rplzzz is right -- you need to set the environment variables accordingly, as described in the [setup guide](http://jgcri.github.io/gcam-doc/gcam-build.html#41-building-with-makefile). I added some Ubuntu-specific instructions in https://github.com/JGCRI/gcam-doc/pull/61.

If you are on Ubuntu 16.04 and installed all the system dependencies using `apt`, the following paths should work:

```
USRLIB = /usr/lib/x86_64-linux-gnu
BOOST_LIB = $(USRLIB)
BOOST_INCLUDE = /usr/include/boost
# For Hector, which uses different definitions
BOOSTLIB = $(BOOST_LIB)
BOOSTROOT = $(BOOST_INCLUDE)
XERCES_LIB = $(USRLIB)
XERCES_INCLUDE = /usr/include/xercesc
JAVA_INCLUDE = /usr/lib/jvm/default-java/include
JAVA_LIB = /usr/lib/jvm/default-java/jre/lib/amd64/server
```

You can either add these lines at the top of `cvs/objects/build/linux/config.system`, or execute each one in the terminal, prefixed with `export` (e.g. `export USRLIB=/usr/lib/x86_64-linux-gnu`, `export BOOST_LIB=$(USRLIB)`, etc...), before running `make`.
