### ISSUE TITLE
Unable to view results

### ISSUE THREAD

**Issue by shashmehro** [JGCRI/gcam-core#34]
Hi,
I am facing an issue everytime I try to view my results
I have run a scenario and when I try to execute a query in the model interface, it appears to be running without any indication of what is going on. When I try to stop the operation, I get an error stating java.lang.NullPointerException.

Please help if someone has observed this issue and knows a way to fix it
[model_interface_log.txt](https://github.com/JGCRI/gcam-core/files/1881880/model_interface_log.txt)
The logs are attached for your reference.

**Comment by kvcalvin** [comment]
Some queries do take a while and there wouldn't be information until it is complete. Canceling the query will lead to a java.lang.NullPointerException. If waiting longer doesn't solve the problem, please re-open the issue and provide more information on which query, what operating system, and which version of java.
