### ISSUE TITLE
GCAM v7 Build Error

### ISSUE THREAD

**Issue by eunhangu** [JGCRI/gcam-core#341]
When building GCAM with Makefile, I got an error related to the boost library..
Here is the error:

g++ -o gcam.exe -O3 -pthread -ggdb -DNDEBUG -DFUSION_MAX_VECTOR_SIZE=30  -MMD -std=c++17 -Wno-deprecated -Wl,-rpath,/data2/eunhan/jdk-20.0.2/lib/server -Wl,-rpath,/data2/eunhan/gcam-core-gcam-v7.0/libs/tbb/lib/intel64/gcc4.8  main.o -lgcam  -L/usr/lib64 -L/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/build/linux -L/data2/eunhan/jdk-20.0.2/lib/server -L/data2/eunhan/gcam-core-gcam-v7.0/libs/tbb/lib/intel64/gcc4.8 -ljvm -lhector -ltbb -ltbbmalloc -ltbbmalloc_proxy -lm -lstdc++fs

/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/build/linux/libgcam.a(interpolation_rule.o): In function `auto ExpandDataVector<boost::mpl::vector<IInterpolationFunction, LinearInterpolationFunction, FixedInterpolationFunction, SCurveInterpolationFunction, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >::getFullDataVector<ParseChildData>(ParseChildData&) const::{lambda(auto:1&)#1}::operator()<boost::fusion::pair<IInterpolationFunction, IInterpolationFunction*> const>(ParseChildData&) const':
/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/util/base/source/../../../util/base/include/expand_data_vector.h:189: undefined reference to `void ParseChildData::processDataVector<boost::fusion::vector<> >(boost::fusion::vector<>)'

/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/build/linux/libgcam.a(interpolation_rule.o): In function `auto ExpandDataVector<boost::mpl::vector<IInterpolationFunction, LinearInterpolationFunction, FixedInterpolationFunction, SCurveInterpolationFunction, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >::getFullDataVector<ParseChildData>(ParseChildData&) const::{lambda(auto:1&)#1}::operator()<boost::fusion::pair<LinearInterpolationFunction, LinearInterpolationFunction*> const>(ParseChildData&) const':
/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/util/base/source/../../../util/base/include/expand_data_vector.h:189: undefined reference to `void ParseChildData::processDataVector<boost::fusion::nil_>(boost::fusion::nil_)'

/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/build/linux/libgcam.a(interpolation_rule.o): In function `auto ExpandDataVector<boost::mpl::vector<IInterpolationFunction, LinearInterpolationFunction, FixedInterpolationFunction, SCurveInterpolationFunction, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >::getFullDataVector<ParseChildData>(ParseChildData&) const::{lambda(auto:1&)#1}::operator()<boost::fusion::pair<FixedInterpolationFunction, FixedInterpolationFunction*> const>(ParseChildData&) const':
/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/util/base/source/../../../util/base/include/expand_data_vector.h:189: undefined reference to `void ParseChildData::processDataVector<boost::fusion::nil_>(boost::fusion::nil_)'

/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/build/linux/libgcam.a(technology_container.o): In function `auto ExpandDataVector<boost::mpl::vector<ITechnology, Technology, DefaultTechnology, IntermittentTechnology, WindTechnology, SolarTechnology, NukeFuelTechnology, TranTechnology, AgProductionTechnology, PassThroughTechnology, UnmanagedLandTechnology, ResourceReserveTechnology, EmptyTechnology, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >::getFullDataVector<ParseChildData>(ParseChildData&) const::{lambda(auto:1&)#1}::operator()<boost::fusion::pair<ITechnology, ITechnology*> const>(ParseChildData&) const':
/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/technologies/source/../../util/base/include/expand_data_vector.h:189: undefined reference to `void ParseChildData::processDataVector<boost::fusion::vector<> >(boost::fusion::vector<>)'

/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/build/linux/libgcam.a(technology_container.o): In function `auto ExpandDataVector<boost::mpl::vector<ITechnology, Technology, DefaultTechnology, IntermittentTechnology, WindTechnology, SolarTechnology, NukeFuelTechnology, TranTechnology, AgProductionTechnology, PassThroughTechnology, UnmanagedLandTechnology, ResourceReserveTechnology, EmptyTechnology, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >::getFullDataVector<ParseChildData>(ParseChildData&) const::{lambda(auto:1&)#1}::operator()<boost::fusion::pair<EmptyTechnology, EmptyTechnology*> const>(ParseChildData&) const':
/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/technologies/source/../../util/base/include/expand_data_vector.h:189: undefined reference to `void ParseChildData::processDataVector<boost::fusion::nil_>(boost::fusion::nil_)'

collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:20: gcam.exe] Error 1
make[1]: Leaving directory '/data2/eunhan/gcam-core-gcam-v7.0/cvs/objects/main/source'
make: *** [Makefile:47: main_dir] Error 2

**Comment by Detachment73** [comment]
the error is solved? this is my error
syntax error: '.'D:\oneapi-tbb-2021.13.0-win\oneapi-tbb-2021.13.0\include\oneapi\tbb\detail\_concurrent_queue_base.h(443): note: while compiling class template member function 'void tbb::detail::d2::concurrent_queue_rep<T,Allocator>::assign(const tbb::detail::d2::concurrent_queue_rep<T,Allocator> &,tbb::detail::d1::cache_aligned_allocator<_Newfirst> &,void (__cdecl *)(int *,const void *)) with [T=int, Allocator=tbb::detail::d1::cache_aligned_allocator<int>, _Newfirst=tbb::detail::d2::concurrent_queue_rep<int,tbb::detail::d1::cache_aligned_allocator<int>>]'D:\oneapi-tbb-2021.13.0-win\oneapi-tbb-2021.13.0\include\oneapi\tbb\concurrent_queue.h(107): note: see reference to function template instantiation 'void tbb::detail::d2::concurrent_queue_rep<T,Allocator>::assign(const tbb::detail::d2::concurrent_queue_rep<T,Allocator> &,tbb::detail::d1::cache_aligned_allocator<_Newfirst> &,void (__cdecl *)(int *,const void *)) with [T=int, Allocator=tbb::detail::d1::cache_aligned_allocator<int>, _Newfirst=tbb::detail::d2::concurrent_queue_rep<int,tbb::detail::d1::cache_aligned_allocator<int>>]' being compiledD:\oneapi-tbb-2021.13.0-win\oneapi-tbb-2021.13.0\include\oneapi\tbb\concurrent_queue.h(134): note: see reference to class template instantiation 'tbb::detail::d2::concurrent_queue_rep<T,Allocator> with [T=int, Allocator=tbb::detail::d1::cache_aligned_allocator<int>]' being compiledD:\oneapi-tbb-2021.13.0-win\oneapi-tbb-2021.13.0\include\oneapi\tbb\concurrent_queue.h(132): note: while compiling class template member function 'tbb::detail::d2::concurrent_queue<int,tbb::detail::d1::cache_aligned_allocator<T>>::~concurrent_queue(void) with [T=int]'D:\GCAM_LIBR\gcam-core-gcam\cvs\objects\util\base\source\manage_state_variables.cpp(94): note: see reference to function template instantiation 'tbb::detail::d2::concurrent_queue<int,tbb::detail::d1::cache_aligned_allocator<T>>::~concurrent_queue(void) with [T=int]' being compiledD:\GCAM_LIBR\gcam-core-gcam\cvs\objects\util\base\source\manage_state_variables.cpp(91): note: see reference to class template instantiation 'tbb::detail::d2::concurrent_queue<int,tbb::detail::d1::cache_aligned_allocator<T>> with [T=int]' being compiled

**Comment by eunhangu** [comment]
I actually tried rebuilding gcam with completely new environment ( I set up the compiler in conda environment ), and I compiled boost (which is not documented in documentation) then it solved. For the tbb, prebuilt version was sufficient for me.

**Comment by eunhangu** [comment]
Since my error was about boost (after compiling boost, problems are solved), I close this issue.
