### ISSUE TITLE
Sectoral net zero pathways

### ISSUE THREAD

**Issue by Kofimoley** [JGCRI/gcam-core#347]
Hi fellow GCAMers, I am curious to know if it is possible to model a net zero or near zero pathway for a particular sector of the economy (example transport) instead of the conventional approach where the net zero pathway is for a region or global. Typically, based on the region or global net zero pathway modelling, one can tell the economy-wide transformations needed to achieve the pathway. However, what if we were interested in knowing just how a particular sector should transition from its current technologies and fuels in order to reach carbon neutrality by that sector (example, assuming one wanted to study the required transformations for a net zero shipping industry by mid-century, and how such an ambition would affect other sectors of the economy such as power, industry, and so on). I have attempted doing this on my own but to no avail. I was hoping to get some guidelines from the contributors and/or users who may have successfully attempted this previously. Would be very happy to get some feedbacks. Thank you. @bpbond @pkyle @zarrarkhan @pralitp @kvcalvin @d3y419 @crvernon

**Comment by pkyle** [comment]
There are a few ways to make sector- or technology-specific policies; the one I've used before is to assign a separate CO2 object to the technologies of interest, in all years. For example, in shipping, you'd want to make an XML file with the following structure:
`
<scenario>

    <world>
        <global-technology-database>
            <location-info sector-name="trn_shipping_intl" subsector-name="International Ship">
                <technology name="Liquids">
                    <period year="1975">
                        <CO2 name="CO2_transport"/>
`

Of course copy that through to all years, for all technologies that you want. The CO2 emitted by the technology will be added to the CO2_transport market, which can then be constrained just as with any other market. The unit is Mt C (i.e., Mt CO2 times 12/44). Examples of the policy structure are in the committed input/policy folder.

`
<scenario>

    <world>
        <region name="USA">
            <policy-portfolio-standard name="CO2_transport">
                <policyType>tax</policyType>
                <market>USA</market>
                <constraint year="2025">350</constraint>
`
