### ISSUE TITLE
Modelling Offshore Wind in GCAM

### ISSUE THREAD

**Issue by fkanyako** [JGCRI/gcam-core#35]
Hi, @pkyle 
I am working on the modeling Wind Energy (both onshore and offshore) in  GCAM 4.4. I have some urgent questions and I will appreciate very much any help I can get.
    
Main question: What is the best approach to adding off-shore wind to  GCAM?
    
1.  It looks like the on-shore wind data enters the system in 
    input/gcam-data-system/energy-data/rawdata/Zhou_wind.csv, processed by 
    the script energy-processing-code/level1/LA114.wind.R.
    
 2. It does not appear that there is any existing structure into which we 
    can plug in data to generate the off-shore wind.
    
3.  Do we need to create a file with the structure of Zhou_wind.csv and 
    create a new R script like LA114.wind.R to process it?
    
 4.  Is this enough to generate the required entries in the 
    global-technology-database and the regional capacity constraints, or is 
    some other "glue" required?
    
5.  Later, we may want to support both fixed and floating offshore wind. 
    Would these need to compete in a separate nest for the available 
    offshore wind resource, and then the composite of these compete with 
    other electricity technologies?
    
Any input on especially question 5 would be particularly helpful.

Happy to receive any assistance I can get.

Thanks

**Comment by pralitp** [comment]
You may want to check @zcranmer's work which is still available at #18.  Where she included offshore wind into GCAM as part of her PHD dissertation.

We have worked to incorporate (a slightly simplified version of) her changes and are _hoping_ it gets included in the next release of GCAM.  However if you are urgently looking to have this capability you may not want to wait for that.

**Comment by towro** [comment]
Hi @fkanyako, 

I am interested in incorporating new technologies into the base GCAM model. I tried using @zcranmer's code as on GCAM v5.2 but got several errors.  Any help on how to do this will be greatly appreciated.
