### ISSUE TITLE
GCAM7.0 error: unable to query GDP in Mac version

### ISSUE THREAD

**Issue by msispah** [JGCRI/gcam-core#351]
Hi, I am not able to query the GDP in ModelInterface in GCAM v7 Mac version. Can someone help in resolving this issue? Thank you.

**Comment by pkyle** [comment]
The query file in `output/queries/Main_queries.xml` should have the correct query, but if you're using a customized query file from an older workspace, or if your model interface is simply pointing to a query file in a different older workspace, then you can just copy the following query:
`
<gdpQueryBuilder title="GDP MER by region">
    <axis1 name="region">region</axis1>
    <axis2 name="Year">nationalAccount[@year]</axis2>
    <xPath buildList="true" dataName="gdp-mer" group="false" sumAll="false">nationalAccount/account[@name = 'GDP']/node()</xPath>
    <comments/>
</gdpQueryBuilder>
`

**Comment by msispah** [comment]
Thank you for reply. I am using the Mac GCAM V7 version. My older workspace is different and is not connected to this. How do I check the correct query file path in Mac version? It does not have model_interface.properties file. I checked the query in Main_queries.xml and it seems ok. I am not sure what is the issue here.
