### ISSUE TITLE
land area sum error on Linux cluster

### ISSUE THREAD

**Issue by vsrikrish** [JGCRI/gcam-core#36]
GCAM 4.4 builds fine on my cluster, but I get the following error when I try to run it with configuration_ref.xml (after seeming to successfully parse the input files and using the initial prices for period 0):
```
ERROR:The sum of land areas in region USA exceeds the land allocation by -8942.4 (-100%)  in period 1
```
I'm using Boost 1.67, Xerces-C++ 3.2.1 (I had to compile this without the "-arch x86_64" flags, if that makes a difference), JDK 8, and the jars.zip and data-system.tar.gz available on GitHub.

**Comment by pralitp** [comment]
We have re-release both GCAM 4.4 and 5.1 with a fix for this issue.

Note the problem did not have to do with Boost, Xerces-C, nor Java.  It had to deal with the code generated by compiling GCAM with GCC 7+.
