### ISSUE TITLE
GCAM FOOD Commodity prices: Consumer Price or Producer Price?

### ISSUE THREAD

**Issue by jiangyongye** [JGCRI/gcam-core#363]
I just want to double-check whether the GCAM OUTPUT FOOD Commodity price is the Consumer or Producer Price.
I read the doc and did not find any information about that. Since I believe the gcam does not have any regionalized food tax or import tax， I assumed the output is producer price based on how the Profit rate(https://jgcri.github.io/gcam-doc/demand_land.html) is calculated.

**Comment by pkyle** [comment]
Note that the prices paid by consumers in GCAM (e.g., sectors/technologies with an input of `regional corn`) don't include any shipping/handling/storage costs. So the consumers' price is the weighted average of the domestic producer prices and the imported commodity price, where the imported commodity price is itself a weighted average of the producer prices in exporting nations.

**Comment by jiangyongye** [comment]
Thank you guys for the detailed explanations! It makes me clear now : )
