### ISSUE TITLE
Energy Units

### ISSUE THREAD

**Issue by fkanyako** [JGCRI/gcam-core#37]
Hi,
In GCAM in (\input\gcam-data-system\energy-data\level2), for the energy technologies, the capital cost/O&M-fixed cost, what units are they in?
The GCAM tutorial says all energy technologies are in $1975/GJ. I don't know if this is referring to the input or output. For example in this "L223.GlobalIntTechCapital_wind_adv"
wind at 2015 capital cost is "620". This cannot be GJ. Please help me out I just want to change the capital and OM-fixed cost for my work. I want to be sure am not getting the unit wrong.

Regards
Franklyn

Thank you

**Comment by pkyle** [comment]
You're correct that these costs are not per GJ--for electricity generation technologies, capital costs are in 1975$/kW, fixed O&M are 1975$/kW/yr, and variable O&M are 1975$/MWh.
