### ISSUE TITLE
Policy-induced economic activity

### ISSUE THREAD

**Issue by dobrien13** [JGCRI/gcam-core#381]
Hi GCAM team,

I was recently asked if the model accounts in any way for the emissions associated with economic behavior induced indirectly by policies. For example, does a transport-sector RES requiring a high share of EV sales induce more mining to represent critical mineral inputs, or would the change only be represented in resource production & refining of petroleum products due to the direct reduction in gas/diesel demand. Any insights or materials to think through this would be so appreciated. 

Thanks,
Dan

**Comment by pkyle** [comment]
Good question--for the most part such interactions are not structurally represented in the public model version, though there's nothing prohibiting this sort of development, and there have been some research branches that have implemented these sorts of linkages. Regarding the specific example, right now "mining energy use" is a final demand whose output (and therefore energy demand) grows with GDP and responds to energy prices; scenarios with high energy prices would see the output of this sector contract, as there's nothing structurally tying its output to electrification technologies, or for that matter to oil and gas exploration and production.
All else equal, reduced gasoline/diesel demand in the transportation sector will reduce refinery energy use, but it won't impact industrial energy use (except indirectly, through impacts on energy prices). The upstream impacts of these choices are structurally

**Comment by dobrien13** [comment]
Thanks for the answer — appreciate your insights. It would be interesting to see if adding in markets for such minerals, e.g. lithium, with depletable resource curves to represent material availability, limited clean-tech development. 

Anyways, appreciate the help!
