### ISSUE TITLE
Hydrogen transmission and distribution questions

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#382]
Hi everyone!

I have two Qs related to the hydrogen transmission and distribution part. Thanks in advance for any guidance on these!

Q1: After the central production of H2 from various pathways, how does the model determine which H2 (produced from different pathways) is transported by pipeline or truck?

My understanding is that the model takes all H2 centrally produced as a pool. So all technologies spread out evenly in pipeline/truck based on their share of each production pathway. (For example, if the solar electrolytic H2 accounts for 10% of the total central H2 production, among all the H2 transported by pipeline, there will also be 10% H2 comes from solar electrolysis. )

If I want to get the how much H2 is transported by pipeline or truck, I can find the value by running the query "hydrogen utilization by technology". 

<img width="1084" alt="image" src="https://github.com/JGCRI/gcam-core/assets/156739336/a5e3813a-f5d6-45d8-8c88-fc75a5b4a0d1">

Q2: In addition, I am also looking for the T&D distance information. It seems the updated document doesn't capture that. I looked back to the HDSAM but still didn't find the info.

I ran into a very recent paper written by the team "Supply and Demand Drivers of Global Hydrogen Deployment." 
Hydrogen delivery from central production facilities is assumed to require 100km of transmissions to the end user. For central green hydrogen, it is assumed to be 500km.

Does the assumption apply to GCAM 7.0 as well?

Greatly appreciate any insights!  Many thanks!!

**Comment by patrickrorourke** [comment]
Hello,

Thanks for your questions!

Q1: Yes, that is correct. The delivery truck and pipeline technologies consume the pooled "H2 central production" sector, and the "hydrogen utilization by technology" query will show the value of how much hydrogen is transported by delivery truck or pipeline.

Q2: The core version of GCAM's assumptions are based on the 100km transmission utilized in the referenced paper, however the additional transmission development for that paper (500km of transmission for central green hydrogen production) is not currently in the core version of GCAM.

**Comment by Youyi77** [comment]
Hi Patrick, thank you so much for these!! Very helpful!
