### ISSUE TITLE
What is the difference  _gSSP and _SSP

### ISSUE THREAD

**Issue by fkanyako** [JGCRI/gcam-core#39]
Hi, 
Is there any significant difference between _gSSP and _SSP. I want to make sure I am able to explain my results and assumptions properly. I couldn't find documentation on this anywhere.

Also I ran a scenario with RCP policy and I get an error coming from this line:
<Value name ="bio_neg_emiss_budget">../input/gcam-data-system/xml/energy-xml/negative_emi
ssions_budget_SSP2.xml</Value>

To run an RCP policy, should I remove this line from the configuration file?

Thanks for your help.

**Comment by kvcalvin** [comment]
The SSP scenarios are the official population and GDP scenarios for the SSPs as published in the literature. The gSSP scenarios were later updated to reflect the near-term changes in the economy. They use IMF GDP growth rate projections from 2010-2020, then converge to the standard SSPs.

We recommend using the gSSPs if the near-term accuracy is important for your research. On the other hand, if the scientific replication of the published SSP is more important for your project, you should use the standard SSPs.

For the RCP policy, I suspect your error would be solved by adding the "carbon_tax_0.xml" file to the configuration file.
