### ISSUE TITLE
Extreme large H2 production cost for CCS related technologies

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#394]
Hi team,

I was running the reference scenario (default after download) and found that these CCS H2 production technologies are extremely high starting from 2020.

![image](https://github.com/JGCRI/gcam-core/assets/156739336/b9e321d2-5822-48a8-805d-1da4417247f4)

I went back and checked the NE costs for these CCS technologies in `hydrogen.xml`. They are within the normal range.

Wondering what could be the cause of these high values or is there any recommendations on which part I should go back to double check?

Thanks for any guidance on this!

**Comment by pkyle** [comment]
All CCS technologies are assigned extremely high costs if the CO2 price is zero. It's just a hack to avoid having the logit sharing equation allocate market share to these technologies when they're always more expensive than what they're competing against, in scenarios and time periods when there's no reason to be capturing the emissions. You can over-ride this just by reading in a nominal carbon price (e.g., 0.1 $/t in all periods). Or, if you compile your own code to build executables and are comfortable revising the C++, the relevant code that does this is in standard_capture_component.cpp, and power_plant_capture_component.cpp:
```
    if( carbonMarketPrice == Marketplace::NO_MARKET_PRICE || carbonMarketPrice == 0.0 ){
        return util::getLargeNumber();
    }
```

**Comment by Youyi77** [comment]
Hi Page! Got it! That makes more sense. Thank you so much.
