### ISSUE TITLE
Clarification on "biomass", "regional biomass", and "delivered biomass"

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#395]
Hi team,

I am a bit confused about the "biomass" concepts in GCAM after I read the online document.

I also found some related figures. Wondering if my understanding is correct:

- The `biomass` in GCAM represents switchgrass, miscanthus, crop residues, eucalyptus, MSW, willow, and sugar crops.
- The components of `regional biomass` and `delivered biomass` are the same as `biomass` as they are subparts of `biomass`.

And what is the difference between `purpose-grown biomass production` and `regional biomass consumption`?

![Schematic-of-biofuel-pathways-in-GCAM-Although-the-default-model-does-not-include](https://github.com/JGCRI/gcam-core/assets/156739336/1c9ee6f1-231e-4393-9a85-9a4b20ac3a29)
![image](https://github.com/JGCRI/gcam-core/assets/156739336/2c086097-456a-4584-8fb4-e8574612b454)

**Comment by pkyle** [comment]
It sounds like your understanding it correct; all of those different biomass streams go into a single blended commodity called `biomass` which is the sole input to `regional biomass` which adds a non-energy cost for processing, and then this is the commodity that goes on to biomass consumers directly, or for sectors that have an additional cost mark-up, to `delivered biomass`. When we refer to "purpose-grown" biomass, that means the biomass_grass and biomass_tree crops in the AgLU module, differentiated from waste by-products of other activities (crop residues, milling and forestry residues, generic municipal and industrial wastes).
Note that sugar crops, corn, soybeans, oil palm, and other oil crops follow a different production pathway; these "first-generation" biofuel feedstocks are represented as standard crops in the AgLU module (output-unit is Mt, not EJ), and are only used for producing biomass liquids in the liquid fuel refining sector. They don't have general energy purposes.

**Comment by Youyi77** [comment]
Hi Page, thank you so much as always! Super helpful.
