### ISSUE TITLE
H2 in GCAM / GCAM-USA

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#398]
Hi team,

A general question regarding the H2 sector.

I want to study the H2 sector in the US on a national level. (Trying to test different subsidies for H2 production techs, different SSPs, etc.)

Since there hydrogen sector in the GCAM-USA is still under development, for now, is it better to use GCAM instead of GCAM-USA even though the latter has a better-tailored dataset (for other sectors) ?

Thanks for any suggestions!!

**Comment by Youyi77** [comment]
Hi @pkyle ! Thank you so much for these detailed explanations. Very helpful!! I actually used GCAM-USA for my analysis, but when I was reading **Core Model Proposal 359: Hydrogen and transportation technology update** from the website:

`"In the core model, GCAM-USA doesn't have a hydrogen module at the state level; hydrogen is represented in the "USA" region, and the electrolysis technologies are disabled because in the GCAM-USA configuration the relevant electricity markets (elect_td_ind, elect_td_trn) don't exist in the USA region."`

Q1: If I am understanding correctly, only the grid electricity water electrolysis (both central and forecourt) is turned off in GCAM-USA. (Or solar/wind/nuclear electrolysis are all shut down?)

I ran the reference GCAM-USA scenario to test and added up all the production from each state. **It seems that there is still some (but limited) H2 produced from grid electricity production in both the central & forecourt production.**

![image](https://github.com/JGCRI/gcam-core/assets/156739336/9eb10081-09af-4c26-a0ab-0fa1924bed77)


Q2: In addition, since other H2 production pathways (i.e., biomass to H2, NG reforming) also rely on electricity (elect_td_ind) as an input, I think my question is how to understand `in the GCAM-USA configuration the relevant electricity markets (elect_td_ind, elect_td_trn) don't exist in the USA region`. Electricity has to exist in the model so does it mean in GCAM-USA, there are no differences between these two?

The multi-state H2 trading sounds really interesting! Hope everything goes smoothly for the H2 sector development! Looking forward to it!

**Comment by pkyle** [comment]
I'm sorry, what I wrote in my prior comment is incorrect. There is a an update to GCAM-USA that creates a full hydrogen module in each state, but it was not merged in time for the June 2023 release, so it's not in the current master branch, or v7 tag, or release. Whenever the next public model update is posted it will include this feature, but I'm not sure when that will be, and for right now I would suggest for any hydrogen market analysis to not use GCAM-USA.

**Comment by Youyi77** [comment]
Got it! Thanks so much! Looking forward to the new release!!!
