### ISSUE TITLE
H2 as a feedstock

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#399]
Hi team,

In the current GCAM, the H2 sector is created only for final energy, not the hydrogen utilization for feedstocks. (Not sure if my understanding is correct!)

Since the refining sector and the chemical end-use sector (which are current major consumers of H2) are also considered to have a large potential to consume green H2, I am wondering if a later GCAM version can add H2 as input feedstock (i.e., in chemicals or hydrogen-derived fuels)?

(I attempted to do so, but it was too complicated!)

Thanks!!!

**Comment by pkyle** [comment]
It's possible this could be done in the future; one major issue however is that the IEA World Energy Balances don't include hydrogen as a PRODUCT (fuel), so base year calibration would require ancillary data on hydrogen production and utilization at petroleum refineries. If we had calibration data on these demands, then going forward we could represent an alternative production technology that uses purchased hydrogen.
The same goes for hydrogen used as chemical feedstocks.
If the IEA World Energy Balances include hydrogen in the future, it's likely that we will accommodate base-year uses of hydrogen, but until then we don't have any plans.

**Comment by Youyi77** [comment]
Hi Page, got it! Thanks so much.
