### ISSUE TITLE
Electricity for NG SMR H2

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#405]
Hi team,

I am wondering why the electricity needed for NG SMR H2 is higher in 2040 compared with 2015, considering efficiency improvement.

I tried to trace back to the H2A models, but it seems that NREL only has "current" version for 2015 but no future version for 2040 for SMR H2 production on the website.

![image](https://github.com/JGCRI/gcam-core/assets/156739336/06b5a90b-f034-45ca-8d8a-eb5d4872d695)

The screenshot is from `H2A_IO_coef_data.csv` in the energy folder.

**Comment by patrickrorourke** [comment]
Thanks for your question!

These values were taken from H2A's v3.2018 files, and I believe the specific file for gas SMR without CCS was titled "future-central-natural-gas-without-co2-sequestration-v3-2018.xlsm". 

I did also check the H2A website [https://www.nrel.gov/hydrogen/h2a-production-archive.html] and it appears the website has removed both the "current" and "future" files for gas SMR without CCS v3.2018.

I'm not sure why the input requirement for electricity increased from the "current" to "future" assumptions, but perhaps slightly more electricity is required for the more efficient use of the main energy/feedstock (gas) for the "future" technology.

**Comment by Youyi77** [comment]
Hi Patrick! Got it, thanks so much for the clarification!!

**Comment by pkyle** [comment]
Also just FYI (keeping the issue closed), the hydrogen assumptions in GCAM 6 and 7 are documented here: https://jgcri.github.io/gcam-doc/cmp/359-Hydrogen_and_transportation.pdf

**Comment by Youyi77** [comment]
Many thanks, Page! This is very helpful.
