### ISSUE TITLE
Could not find double: discountRate/discount-start-year

### ISSUE THREAD

**Issue by PaulBehrens** [JGCRI/gcam-core#43]
Hi there, 

Thank you for all your efforts to document and develop GCAM. I am trying to get a feel for what happens to technology mixes under standard runs but with different discount rates (if you know of work that investigates this I would be really interested). 

When I run with find-path enabled (I believe I have to run with this for this use case), I receive the messages "Could not find double: discountRate" and "Count not find int: discount-start-year" after the model run is completed. Everything is default as came with the download package. These messages appear for the two policy files I have looked at so far "forcing_target_3p7" and "...4p5" Discount rate seems to be set in the policy file, so I'm wondering where these should be set or if this might be a bug either as a message or something that is not being defined?

Many thanks again,

Paul

**Comment by pkyle** [comment]
Paul,
These are variables that can be set in the configuration.xml file; discountRate is a "double" and discount-start-year is an "int". If they aren't explicitly set in the configuration.xml file, they default to 0.05 and 2005, respectively; you can see the default values in [total_policy_cost_calculator.cpp](https://github.com/JGCRI/gcam-core/blob/master/cvs/objects/containers/source/total_policy_cost_calculator.cpp). The warning messages are intended to let users know that these user-configurable variables are just taking default values.
Note that these variables in the warning message are only used in calculating cumulative discounted policy costs; the `path-discount-rate` that you see in the policy/forcing_target*.xml files is different. That is the rate of escalation of the carbon price as the model is running iteratively to try to hit an end-of-century target. Note also that there are other discount rates used throughout GCAM such as for amortizing capital costs in different sectors, or valuing carbon on land; these would be changed through different input files.
Page

**Comment by PaulBehrens** [comment]
Dear Page, 

Thanks a lot for the quick response. Would there happen to be any documentation listing where all the discounting occurs? I had a search for mentions of discount/amortization etc. through the input xml files but I'm sure I didn't pick up all of them. Thanks again, Paul

**Comment by pkyle** [comment]
Good question! There was a response to a similar question a number of years ago that isn't in the current documentation so I'll copy the response here:
There are a variety of discount rates that one can find in various files used in data processing, model input, and model configuration. The discount rates used for amortization of overnight capital costs are not in the XML files, and are different from the ones used in discounting policy costs or generating Hotelling emissions price pathways. Note that electricity generation technology costs are read to the model in disaggregated form, with separated capital costs, variable O&M, and fixed O&M. Capital costs are assigned a "fixed-charge-rate" which is determined from the amortization rate and the lifetime of the technology. All other non-fuel costs read to the model are levelized (i.e., expressed per unit of service output). Many of these are calculated from explicit capital costs and exogenous assumptions about lifetimes and discount rates. Anyway, here are some different rates that might be useful:
15%: Amortization of overnight capital costs of fossil, biomass, and nuclear power plants.
12.5%: Amortization of overnight capital costs of renewable electric technologies (central PV, solar CSP, wind, geothermal).
10%: Amortization of capital costs of building technologies, including rooftop PV.
10%: Amortization of purchase prices of cars and light trucks.
5%: “interest-rate” assigned to each region, used in calculating the value of carbon in the land.
5%: Default “discountRate” used in converting annual policy costs to discounted cumulative policy costs. This is an “int” in the configuration file.
5%: Default “path-discount-rate” used by the target finder, as it iterates to find a carbon price trajectory that meets a radiative forcing or CO2 concentration target."
