### ISSUE TITLE
Erroe in GCAM7 modelface 'gdp-per-capita-ppp' unit?

### ISSUE THREAD

**Issue by jiangyongye** [JGCRI/gcam-core#430]
I was confused about the unit in GCAM7 Modelface  'gdp-per-capita-ppp'  section, which is million 1990$
For example, SSP5 USA 2015 gdp-per-capita-ppp are
33.2204 million 1990$
which is not make sense.
Could anyone help me with that?
![image](https://github.com/JGCRI/gcam-core/assets/49706086/7246a05e-1903-4399-9029-759419036ee2)

**Comment by jiangyongye** [comment]
Follow up!
I checked the file **zsocio_L102.GDP.R**
it said
**The scenarios generated include the SSPs and the gSSPs (SSPs modified by
#' near-term IMF projections).  GDP outputs are in millions of 1990 USD, Market
#' Exchange Rate (measured in 2010) is used for foreign currency.  Per-capita
#' values are in thousands of 1990 USD.**

so the unit should be thous 1990USD which it make much more sense : )

And i think why this error happen in GCAM7 but not happend in GCAM6
Because GCAM7 added marco_economy module,
in GCAM 7 the code in Main_queries.xml for GDP-PER-CAPITA
changed from
```
<gdpQueryBuilder title="GDP per capita MER by region">
            <axis1 name="region">region</axis1>
            <axis2 name="Year">gdp-per-capita-mer</axis2>
            <xPath buildList="true" dataName="gdp-per-capita-mer" group="false" sumAll="false">GDP/gdp-per-capita-mer/text()</xPath>
```
to 
```
        <gdpQueryBuilder title="GDP per capita PPP by region">
            <axis1 name="region">region</axis1>
            <axis2 name="Year">nationalAccount[@year]</axis2>
            <xPath buildList="true" dataName="gdp-per-capita-ppp" group="false" sumAll="false">nationalAccount/account[@name = 'gdp-per-capita-ppp']/node()</xPath>
```

And i believe in nationalAccount the units are only million 1990US$ based on **zsocio_L180.GDP_macro.R**
That's why it appear million 1990US in modelface, correct me if i understand wrong ： ）！

**Comment by realxinzhao** [comment]
@jiangyongye good catch! 

Yes, there were some unit discrepancies. It seems population in National Account should be thous as well. We will try to update these. Thanks!
