### ISSUE TITLE
Issue with model output

### ISSUE THREAD

**Issue by ishanjoshi19** [JGCRI/gcam-core#454]
I am new to the GCAM model, I have successfully installed it and ran the model for the first time. However, even after changing the configuration file I still see the same output for different scenarios. If I want to choose a different policy, for example, carbon_tax_0, do I just add it in the `<ScenarioComponents> `section of `configuration.xml `or are there other changes I need to do as well? Thanks.

**Comment by pkyle** [comment]
Most policies can be run just by adding XML files to the scenario components section of the configuration. Note that `carbon_tax_0.xml` isn't going to make any changes on its own; it assigns a default carbon price of 0, for a CO2 market that needs to be defined elsewhere (CO2_LTG = long term global). If you just replace CO2_LTG with CO2 in the numbered carbon tax files (e.g. `carbon_tax_10_5`), then you won't need another XML file to define the CO2_LTG market. Also one thing to be aware of, in recent versions of the model I've sometimes had an issue where a policy tax or constraint needs to be specified in all regions, not just one. So if switching the market to CO2 still doesn't cause any difference from the reference, then I would suggest copying the price trajectory 31 times to all of the different regions.
If you're running a policy that will use `target-finder`, then you'll need to set the Bool `find-path` to 1, and point to the relevant target in the Files section. This is what is done in the `configuration_policy.xml` file.

**Comment by ishanjoshi19** [comment]
Thanks for the detailed information!
