### ISSUE TITLE
Question Regarding GCAM's Historical Simulation Logic

### ISSUE THREAD

**Issue by jiangyongye** [JGCRI/gcam-core#462]
After reading through the GCAM documentation for quite some time, I still have a question about the purpose of historical simulations in GCAM. From my understanding, GCAM requires a large number of constraints during historical simulations (before 2015) to ensure that the model’s results align with reality.

I’m unsure which of the following best explains GCAM’s logic:

A: Is it because GCAM lacks sufficient mechanisms (e.g., extreme events like economic crises or natural disasters), which is why many constraints are necessary? In this case, is GCAM trying to replicate history but is limited by the mechanisms it currently includes?

B: Should I understand that GCAM's historical simulation is not really attempting to replicate history, but instead is focused on continuous calibration (similar to the spin-up process in CESM) to create a good initial condition for the 2015-2100 simulation?

The reason I'm asking this is that if we have accurate data for 2015, why not just start the simulation from 2015 directly, instead of performing historical simulations?

**Comment by ssmithClimate** [comment]
For the most part, we are not simulating the historical period in the same sense that an ESM spin's up. 

For each historical year presented in the model, we match exactly (to within some tolerance) calibration values that are determined from historical data (however, for agricultural production, we use a rolling average so we are not calibrating to climate-induced inter-annual yield fluxuations). So except for the last base-year period, the historical values do not impact future results (fossil resource extraction is one exception). 

The model is solving for each of the historical periods, however it is being constrained to match the calibrated values derived from historical data. The main endogenous model result over the historical period are share-weights, which are the main adjustable parameter used to match historical values. 

The model results for the last historical base-year period, however, do impact the future trajectories. Model parameters and results for the last historical base-year period, such as inferred capital stocks, prices, and technology and sub-sector weights do impact future model results.

**Comment by jiangyongye** [comment]
Thank you so much for the detailed response, Smith! Everything is clear to me now!
