### ISSUE TITLE
Confusion about 'Food Demand per Capita' and How to Model a Diet-Shift Scenario?

### ISSUE THREAD

**Issue by jiangyongye** [JGCRI/gcam-core#471]
I've been working on running a diet-shift scenario in GCAM7 recently. First, I would like to express my gratitude to Xin Zhao @realxinzhao  and Page Kyle @pkyle for their detailed responses in issue #311 regarding similar questions—they have been incredibly helpful.

However, I have a few points of confusion:

I noticed that the 'food demand per capita' for staples and non-staples combined shows a very high daily calorie intake per person (for example, around 3200 kcal in the U.S. in 1990). However, based on FAO recommendations and common knowledge, the average daily calorie intake should typically be around 2000-2500 kcal. I suspect this discrepancy might be due to GCAM accounting for food waste, meaning that the 'food demand per capita' represents the total calories of food purchased rather than the actual calories consumed（ate）. Could you confirm if this assumption is correct?

Additionally, I'm trying to run a diet-shift scenario, but my approach differs from what was discussed in issue #311, and I'm unsure if it's valid.

My approach is as follows: Given that we have future population projections, if my scenario assumes that people follow standard intake guidelines regardless of income, could I directly modify the 'calOutValue' in the food_demand.xml file for the years 2020-2100? I would set the  'calOutValue'  for each food type in each country according to the population, similar to how historical simulations are done. Would this be a viable method?

**Comment by pkyle** [comment]
Feel free to double check us; our reported per capita food consumption should be the same as what is in the food balance sheets maintained by FAOSTAT. GCAM tracks these flows both in mass (input to FoodDemand sectors) and in calories (output thereof). According to FAO’s definition, we do expect this number to be higher than what is actually consumed by people: “It is important to note that the quantities of food available for human consumption, as estimated in the food balance sheet, reflect only the quantities reaching the consumer. The amount of food actually consumed may be lower than the quantity shown in the food balance sheet depending on the degree of losses of edible food and nutrients in the household, e.g. during storage, in preparation and cooking (which affect vitamins and minerals to a greater extent than they do calories, protein and fat), as plate-waste, or quantities fed to domestic animals and pets, or thrown away.”
My own interpretation is that their estimates of food consumption are probably based on sales, and only first-use of each commodity. So for example the fry oil that is purchased by restaurants is classified as food consumption, even though a large portion of it is not actually eaten, and is later repurchased by biodiesel manufacturers. Again this is just my assumption; I've never seen their methodology spelled out to that level of detail. But yeah from what I remember, they have Americans eating something like 60 grams per person per day of soybean oil, which would be pretty insane if it were correct!

**Comment by realxinzhao** [comment]
And yes, we have the food calorie supply (not intake) from FAO which includes food waste.

**Comment by jiangyongye** [comment]
Thanks you guys for detailed reply as always! (Sry for late reply)
