### ISSUE TITLE
Non energy costs in the Transportation sector

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#473]
Hi GCAM Team,

Under the transportation sector, I am wondering why the tab ` transport tech non-energy cost ` for each trn technology is higher than the `costs of transport techs`? I think the latter is the sum of non-energy costs and energy costs.

I assume that the cost of each technology = fuel costs + non-energy costs + any carbon penalties.

Thanks so much!

![image](https://github.com/user-attachments/assets/dfe510a6-c904-4343-8d13-f2cb897d29cb)

**Comment by patrickrorourke** [comment]
Good question!

- The “transport tech non-energy cost” query displays the value that is read to the model, and the units are 1990$/veh-km (but has mis-reported units in the query).

- The “cost of transport tech” query displays the value in per service-km units (1990$/pkm, 1990$/tkm).
