### ISSUE TITLE
Target module_aglu_L162.ag_prodchange_R_C_Y_GLU_irr failed

### ISSUE THREAD

**Issue by rongqizhu** [JGCRI/gcam-core#477]
Hi GCAM team,

I am currently able to `driver() ` in GCAM v6, but when i try to `driver()` in GCAM v7.1 using the same R package, an error occurrs in this chunk:
![Image](https://github.com/user-attachments/assets/632a0f92-af1e-4b50-a568-c71738aaa34d)

I  have tried to update **dplyr** from **1.0.6** to **1.0.10**, but still have the same error. My R package information is as follows: 
![Image](https://github.com/user-attachments/assets/fdc691e6-77fc-4356-89ec-7675e5e956e4)

Thanks a lot!

**Comment by rongqizhu** [comment]
> Hi, it doesn't seem package versions are the issue for you. You can add `mutate(yield_kgHa = as.numeric(yield_kgHa)) %>%` before grouping in L115 of the `input/gcamdata/R/zaglu_L162.ag_prodchange_R_C_Y_GLU_irr.R` chunk to resolve this. The code should look like as shown here: https://github.com/JGCRI/gcam-core/blob/master/input/gcamdata/R/zaglu_L162.ag_prodchange_R_C_Y_GLU_irr.R#L115C7-L115C54

Thanks for your help, the issue has been resolved.

**Comment by realxinzhao** [comment]
Note that this one has been resolved in GCAM7.2:
https://github.com/JGCRI/gcam-core/releases/tag/gcam-v7.2

**Comment by rongqizhu** [comment]
> Note that this one has been resolved in GCAM7.2: https://github.com/JGCRI/gcam-core/releases/tag/gcam-v7.2

Thank you for the reminder. 
By the way, when running GCAM7.1, I also found a similar small error in` zaglu_L202.an_input.R`, which has also been resolved in GCAM7.2. This might be helpful for those planning to run GCAM7.1
![Image](https://github.com/user-attachments/assets/100f47f1-7946-4516-904b-c9b70e36da5d)
