### ISSUE TITLE
Calculation of forest fire emissions in GCAM

### ISSUE THREAD

**Issue by CGL5230** [JGCRI/gcam-core#481]
Hello GCAM team,

I'm looking to understand how GCAM-core models carbon emissions from forest or vegetation fires. Specifically, could you point me to the sections or modules where fire emissions are parameterized or configured?

I see “**Emissions in the agriculture and land use system can be driven by output (e.g., for crop production) or** **land area (e.g., for forest fires**). in the [documentation(doc),](https://jgcri.github.io/gcam-doc/emissions.html) but I can't find the corresponding code under this [path,](https://github.com/JGCRI/gcam-core/tree/master/cvs/objects) am I looking for the wrong one?

![Image](https://github.com/user-attachments/assets/9027eeef-5222-4abf-b659-f09ceef4b249)

In Carbon Emissions [section](https://jgcri.github.io/gcam-doc/land.html#carbon-emissions),It looks like forest fires are considered a type of land use type conversion, **if I want to get emissions from forest fires separately, where are the corresponding formulas and codes?**

![Image](https://github.com/user-attachments/assets/61071210-85e4-47ed-8707-ccbbd809ed0f)

Thanks for your help!

**Comment by pkyle** [comment]
The modeling approach is different for the non-CO2 emissions, as compared to the CO2 emissions, for open biomass burning. Non-CO2 emissions are more or less taken directly from inventories, though there is a distinction in the model between emissions related to deforestation (i.e. clearing of forest for other uses) as opposed to forest fires on lands that are assumed to remain as forests afterwards. From the model's perspective, forest fires do not amount to land use change, and do not produce net CO2 emissions, but do produce non CO2 emissions. Deforestation (i.e., net transition of land from forest to other uses, at the scale of the land use regions in the model) produces net CO2 emissions based on the difference in carbon density between forest and the land use types that increased. The net carbon emissions or sequestration from changes in land use is estimated using a simple carbon cycle model.
To your question about where in the model to find the relevant information, most of the key parameters for the carbon cycle modeling (and LUC CO2 emissions) are found in the `input/gcamdata/xml/land_input_*.xml` files, where each land use type is assigned terminal vegetative carbon density, terminal soil carbon density, and mature age, which is the number of years for reaching terminal vegetative carbon density. Non-CO2 emissions and emissions factors are assigned in (same folder) `all_unmgd_emissions.xml` and `all_aglu_emissions_IRR_MGMT.xml`

**Comment by pkyle** [comment]
I would not recommend changing `input-emissions`, as this will change the base year quantity of emissions, which would effectively diverge the model's results from the underlying inventory estimates. The model is using the input emissions, divided by the land cover, to calculate an emissions coefficient, emiss-coef. You can calculate what this coefficient is from the base year data, and then in future periods, read in that emissions coefficient multiplied by some scaler if you want to increase or decrease the emissions rate. For example:
```
                <AgSupplySubsector name="ForestFire_PacArctic">
                    <UnmanagedLandTechnology name="ForestFire_PacArctic">
                        <period year="2025">
                            <Non-CO2 name="SO2_1">
                                <emiss-coef>0.001</emiss-coef>
```
That revised coefficient will over-ride whatever the model calculated from the base year data. The units are Tg of the NonCO2 per thousand km2, or kg per square meter.

To the question about carbon and CO2, yes for the temporal and spatial scales at which land is being represented in gcam, forest fires are assumed carbon neutral; what drives CO2 emissions and uptake in GCAM’s carbon cycle model is land use change. The approach that we take for carbon cycle modeling is similar to Houghton who published a number of papers in the late 1990s; it is possible that forest fires are folded into the assumed terminal vegetative carbon contents of forests, which in his models were done at the continental scale I believe. Even if they were, the terminal vegetative carbon density of a land use type isn't something that can be changed over time in GCAM.

**Comment by ssmithClimate** [comment]
Sounds like there was some confusion here, the question seemed to be about CO2 emissions. GCAM calculates CO2 emissions from land-use change using changes in land-allocation. So if the area of forest reduces, that implies a net carbon emission as the forests are converted to other uses.

At present, GCAM implicitly assumes that forest and grassland fires are operating in steady state - that the CO2 emitted by fires is taken up by re-growth. If the frequency and severity of forest fires increase, then in effect, what this would do would be to decrease the average carbon content of forests. We don't include this effect in GCAM currently, but you could estimate that exogenously.

**Comment by CGL5230** [comment]
I see. Thank you @pkyle @ssmithClimate ! So, if  I want to reduce fire emissions by 30% then that means `emiss-coef` **needs to be multiplied by 1.3.** if I understand you correctly. Like:

                <AgSupplySubsector name="ForestFire_PacArctic">
                    <UnmanagedLandTechnology name="ForestFire_PacArctic">
                        <period year="2025">
                            <Non-CO2 name="SO2_1">
                                <emiss-coef>0.0013</emiss-coef>

**Comment by ssmithClimate** [comment]
The other way around. The emissions coefficient is "Emissions / Driver", so divide by 1.3 to reduce emissions.

**Comment by CGL5230** [comment]
Thank you @ssmithClimate . I was trying to design a scenario combining a 30% reduction in fires with an increase in the carbon tax, but so far it seems that GCAM doesn't seem to be concerned with CO2 emissions from fires, so maybe the scenario I designed is no different from the scenario with a carbon tax increase alone.

**Comment by ssmithClimate** [comment]
Fires in gcam only impact non-CO2 GHG and air pollutant emissions, not CO2. CO2 is determined by net land-use change - which can be impacted by a carbon price, depending on your setup. See further info here:

https://jgcri.github.io/gcam-doc/policies.html

**Comment by CGL5230** [comment]
I previously intended to use GCAM to explore the control of fires and land-use changes. However, based on the current version of GCAM, it seems that this would not affect land-use changes.
