### ISSUE TITLE
Problem running GCAM 4.3

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#49]
Hi 
I am trying to running GCAM 4.3 on a new windows 10 computer, but keep getting  the error shown in the snapshot. To fix the problem I have tried running GCAM on various version of Java SE 6 & 7 all to no avail. Thanks in advance for any form of help and suggestions. 
  
![image](https://user-images.githubusercontent.com/34580273/51246517-9fc7d200-1958-11e9-9107-f8408ee5a124.png)

**Comment by pralitp** [comment]
This error seems to indicate that you need to install the Microsoft Visual Studio 2013 redistributable package.  Be sure to install the x64 version:
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by RawisWar** [comment]
Thanks it worked !!!
