### ISSUE TITLE
Future non-CO2 emissions from forest fires not found in all_unmgd_emissions.xml

### ISSUE THREAD

**Issue by CGL5230** [JGCRI/gcam-core#490]
Hi,GCAM team!

I've recently been trying to modify non-CO2 emissions from forest fires for the SSP126 scenario.This question is related to my previous [question](https://github.com/JGCRI/gcam-core/issues/481#event-15335995518). 

As your suggestion, i try to modify the `emission_cof` in ` all_unmgd_emissions.xml`. But I didn't find an input value that corresponds to future non-CO2 emissions.**It looks like the time is only set from 1975-2015.** 

![Image](https://github.com/user-attachments/assets/a02a38f5-57b0-44a6-a6fa-bf793bfc2f94)

I didn't find anything like ‘all_unmgd_emissions_ssp1.xml’ or anything like that. Where can i find the `emission_cof` for future forest fire non-CO2 emissions？

**Comment by pkyle** [comment]
`emiss-coef = input-emissions / driver`
For forest fires, the driver is the land allocation of the given region, land use type, basin, and year. For deforestation, the driver is the reduction in land allocation from the prior time period. Note that deforestation only returns emissions in time periods with net reduction in forest land. Whatever coefficient is calculated by the model in the final available base year (usually 2015) is passed forward to all subsequent time periods, but can be over-ridden by a user-specified value.

**Comment by CGL5230** [comment]
Thanks @pkyle
