### ISSUE TITLE
GCAM 4.3 installation

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/gcam-core#5]
I created an install script for 4.3 on Macs (see https://bitbucket.org/snippets/plevin/qodzL/install-script-for-gcam-v43-on-mac) that several users found helpful at the workshop. After running it, however, the libs jvm symlink still needs to be set up by running the run-gcam.command script one time only, after which ./Release/objects runs the model.

Suggestions:
1. Make the script available to users
2. Add the symlink stuff from run-gcam.command to this script
3. Remove the run-gcam.command script since it's broken

**Comment by michaeljaywalsh** [comment]
I'm trying to compile GCAM in Ubuntu and I think I might be running into a similar problem.
make recipe is failing at this command:
```
g++ -o gcam.exe -O2 -ggdb -DNDEBUG  -MMD -std=c++11 -Wno-deprecated -Wl,-rpath,/home/michael/libs/xercesc/lib -Wl,-rpath,/usr/lib/jvm/java-1.9.0-openjdk-amd64/jre/lib/server    main.o -lgcam  -L/usr/local/lib -L/home/michael/libs/xercesc/lib -L/home/michael/gcam-core/cvs/objects/build/linux -L/usr/lib/jvm/java-1.9.0-openjdk-amd64/jre/lib/server   -lxerces-c -ljvm -L/home/michael/libs/boost-lib/stage/lib -Wl,-rpath,/home/michael/libs/boost-lib/stage/lib -lhector -lboost_system -lboost_filesystem   -lm 

/usr/bin/ld: cannot find -ljvm
```
`-ljvm` is set as the `JAVALINK` variable in configure.gcam  
I can compile sucessfully with Java off (e.g. `#define __HAVE_JAVA__ 0`) which leaves this command out, but this leaves me without database capability. There appear to be a couple of suggestions on stackoverflow regarding this command and setting up a symbolic link to libjvm.so, but so far my fiddling around has been unsuccessful.

**Comment by pralitp** [comment]
@michaeljaywalsh, I think Rick's issue is Mac specific and yours is unrelated.  Could you open new issue and we can work through it there.

**Comment by davidrmorrow** [comment]
For anyone having trouble opening ModelInterface on Mac OS X:

After using Rich's very helpful script (thanks, Rich!), everything worked perfectly except that I couldn't launch ModelInterface. Double-clicking on the icon in Finder would prompt the "opening" animation in the Dock, but then it would disappear without opening the application.

On Mac OS X Sierra, I found that I run ModelInterface by clicking on the universalJavaApplicationStub located inside the ModelInterface.app package. I found it helpful to create an alias for that file in the main ModelInterface folder. To do that, follow these steps:

1. Open **Terminal** and navigate to the ModelInterface folder in your GCAM installation.
2. Enter the following code:

`ln -s ModelInterface.app/Contents/MacOS/universalJavaApplicationStub ./launchModelInterface`

Or follow these steps:

1. In **Finder**, navigate to the ModelInterface folder in your GCAM installation.
2. Right-click or ctrl-click the ModelInterface icon and select _Show Package Contents_.
3. Navigate to _Contents > MacOS_.
4. Right-click or ctrl-click the `universalJavaApplicationStub` file and select _Make Alias_.
5. Rename that alias (e.g., to `launchModelInterface`) and drag it to the ModelInterface folder in a new **Finder** window.

You can then open ModelInterface by clicking on the `launchModelInterface` icon in **Finder**.

I hope this save someone else some time!

P.S. I experienced a similar problem with ModelInterface when I installed GCAM 4.2. I solved that one by uninstalling Java JDK 1.8 and installing a legacy version of Java 1.6. That didn't work for GCAM 4.3, and it's less than ideal anyway.

**Comment by AxDef** [comment]
Hi

I am new to GCAM, I understand that it is quite difficult to set up the proper Java version. I tried to understand solutions yet I still have this issue when I launch : 

./run-gcam.command

gives me : 

dyld: Library not loaded: @rpath/libjvm.dylib

Any idea ?

**Comment by dodsonjc3** [comment]
@AxDef I am having the same problem, and have tried all the trouble shooting techniques recommended on the GCAM documentation. Did you ever find a solution?

**Comment by AxDef** [comment]
Hello !

Yes, now the installation is perfect for me. I remember that my problem came from an R package.

It has been a while now. I remember that I reinstalled the Java environment and R version as required.
I used R studio to install the R package needed and it finally worked for me.
