### ISSUE TITLE
Recreate XML files from CSV?

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#50]
How do I re-export XML files from CSV using v5.1.2? I tried to do this following the steps outline in the 2017 Tutorial (opening the CSV in ModelInterface and selecting the headers file) but I get an error in the ModelInterface when trying to do this.

**Comment by pkyle** [comment]
This isn't really a capability that has been maintained through to 5.1.2; assuming you're trying this from (manually modified) files in the `gcamdata/outputs/` directory, those files don't have the necessary header rows, and the columns aren't sorted in the correct order.
If you're just doing this for one or two files, you can re-order the column names according to the ordering specified in:
`gcamdata/data-raw/generate_package_data.R`
Just search for the relevant ID string from the CSV file (e.g., the ID string from `L203.BaseService.csv` is `BaseService`), and the correct code line (e.g., `level2_data_names[["BaseService"]]`) will tell you the column order. Then, you'll need to pre-pend the table with the following rows:
```
INPUT_TABLE
Variable ID
<IDstring>
<blank row>
```
Save it, and convert it to XML using the header file: `gcamdata/inst/extdata/mi_headers/ModelInterface_headers.txt`

**Comment by rjplevin** [comment]
To support automation, it would be great if the function `generate_level2_data_names` that builds the table of column info were in a separate file, so that it could be loaded without running the other top-level code in generate_package_data.R. 

For example, I'd like to write a short R script that outputs a CSV that I can load in pygcam:

```
fn = "/tmp/columns.csv";
con = file(fn, open="w")

for (name in names(LEVEL2_DATA_NAMES)) {
  cat(paste0(name, ",", paste(LEVEL2_DATA_NAMES[[name]], collapse=","), "\n"), file=con)
}

close(con)
```

But I had to copy & paste the function from the R file...

**Comment by robbieorvis** [comment]
Thanks all.

I was able to do this using by following the GCAM Data System download and install instructions, and running driver(stop_after), referencing the module that produces the requisite input XML file for GCAM. Not automated, but relatively fast. The documentation for the Data System is quite good, so thanks for putting that together.
