### ISSUE TITLE
Example of modeling a CAFE standard in GCAM?

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#54]
Hello,

Does anyone have an example of a modeled CAFE standard in GCAM? Would be interested in seeing the policy XML file if so.

Thanks.

**Comment by pkyle** [comment]
I do, though it's in the old data system format. The XML file is a bit tough to decipher because of all of the unit conversions that are hardwired into the "tranTechnology" inputs and outputs. But the CSV input file is read by the enclosed R code file to produce the XML file; let me know if that's not clear. Note that this was a CAFE policy in that it only applies to new vehicles, not stock averages. Each year and vehicle size class is assigned its own CAFE target.
[IntensityTarget.zip](https://github.com/JGCRI/gcam-core/files/2973408/IntensityTarget.zip)

**Comment by robbieorvis** [comment]
I finally had a chance to review this more carefully, and I think I understand how it works. It would be really interesting to do a similar policy, but as a ZEV mandate. I think you could model this as BEV vehicles in each vintage producing credits for that vintage as a secondary res output, with all vehicles types requiring those credits as a minicam-energy-input. The challenge, I think is in the conversion, correct? If I understand correctly, you would need to convert million passenger KM out (the secondary output) to EJ input based on the efficiency of each vehicle type in each vintage year. Is there an (relatively) easy way to adapt the .R script you included above to handle that?

**Comment by pkyle** [comment]
Yeah, that should be possible, with a few modifications on the existing intensity cap (i.e., CAFE standard) methods. Where the intensity caps have all vehicle technologies producing credits equal to their intensity cap value (in MJ per vehicle-km) divided by their load factor and multiplied by a fixed unit conversion (CONV_MJ_TJ, equal to 1e-6), here only the BEVs would produce credits. I believe they would be equal to 1e-6 divided by the load factor. And, on the input side, all technologies (not just BEVs) would be assigned an input coefficient equal to the target BEV share
[intensity_caps_for_gcamdata.zip](https://github.com/JGCRI/gcam-core/files/3397432/intensity_caps_for_gcamdata.zip)
. So, in the enclosed code (which works for GCAM 5.1.2, not 5.0 or prior; let me know if you want instructions for the corresponding fileset that I posted in March), first replace "Intensity" with "BEV share" in lines 61 and 72. Then in lines 45-61, line 61 will be
`mutate(minicam.energy.input = paste(year, tranSubsector, "BEV share"))`
Line 72 will be
`mutate(res.secondary.output = paste(year, tranSubsector, "BEV share"),`
And line 73 will be
`output.ratio = round(1 / loadFactor * CONV_MJ_TJ, energy.DIGITS_trnRES),`
The code block in lines 69-75 should also include a line to filter only the BEV technologies:
`filter(grepl('BEV', tranTechnology))`
Oh and the values in `A2542.IntensityCaps.csv` should be the desired BEV shares for the given vehicle size class and model year. Fingers crossed that this will do the trick! Sorry I don't have a chance to test this out.

**Comment by robbieorvis** [comment]
This is great, thanks! I will give it a shot and report back, including uploading of files if it works.

**Comment by robbieorvis** [comment]
FYI, tried this, but got this error in RStudio:

Error: Can't subset with `[` using an object of class NULL.
Call `rlang::last_error()` to see a backtrace 
17.
stop(cnd) 
16.
abort(error_unsupported_index(j)) 
15.
check_names_df(j, x) 
14.
`[.tbl_df`(data, , LEVEL2_DATA_NAMES[[column_order_lookup]]) at xml.R#54
13.
data[, LEVEL2_DATA_NAMES[[column_order_lookup]]] at xml.R#54
12.
add_xml_data(., L2542.StubTranTechRES_caps, "StubTranTechRES") 
11.
function_list[[i]](value) 
10.
freduce(value, `_function_list`) 
9.
`_fseq`(`_lhs`) 
8.
eval(quote(`_fseq`(`_lhs`)), env, env) 
7.
eval(quote(`_fseq`(`_lhs`)), env, env) 
6.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
5.
create_xml("IntensityCap_trn.xml") %>% add_xml_data(L2542.StubTranTechCoef_caps, 
    "StubTranTechCoef") %>% add_xml_data(L2542.StubTranTechRES_caps, 
    "StubTranTechRES") %>% add_xml_data(L2542.PortfolioStdConstraint_RES, 
    "PortfolioStdConstraint") %>% add_precursors("L2542.StubTranTechCoef_caps",  ... at zchunk_batch_IntensityCap_trn_xml.R#29
4.
module_energy_batch_IntensityCap_trn_xml("MAKE", list(L2542.StubTranTechCoef_caps = structure(list(
    region = c("USA", "USA", "USA", "USA", "USA", "USA", "USA", 
    "USA", "USA", "USA", "USA", "USA", "USA", "USA", "USA", "USA", 
    "USA", "USA", "USA", "USA", "USA", "USA", "USA", "USA", "USA",  ... 
3.
do.call(chunk, list(driver.MAKE, all_data)) at driver.R#14
2.
run_chunk(chunk, all_data[input_names]) at driver.R#290
1.
driver(stop_after = "module_energy_batch_IntensityCap_trn_xml")

**Comment by pkyle** [comment]
Oh well! I'll look into it in the next few days and revise what I sent (sorry, can't look further today)

**Comment by robbieorvis** [comment]
That's alright! I appreciate the help. No rush.

Thanks.

**Comment by pkyle** [comment]
Also what GCAM version are you running? I guess all that matters is whether it's more or less than 5.1.

**Comment by robbieorvis** [comment]
5.1.2

**Comment by robbieorvis** [comment]
@pkyle I think that there may also be an issue where plugging in the values and restructuring as you've suggested doesn't quite work here. Based on the GCAM Data System files you sent, it looks like the place where the cap comes into play is in the output multiplier for the res-secondary-output, which I can see but I don't fully understand. Under the current set of functions it then would appear that the supply of credits is equal a total amount of energy based on the distance traveled by vehicles (output units in transportation million pass-km and the output ratio formula is MJ/vkm * 10^-6 / load factor, which nets out out to MJ). 

In any case, the instructions above say to delete out the MJ/vkm in the output ratio line, but that means there is no place where the BEV share is actually being used in the GCAM Data System file, so that won't work.

I think I'm close to getting this, it's just the unit conversions that are throwing me off.

It seems like the output-ratio for BEVs should be equal to 10^-6/load factor, which when multiplied by the output (million pass-km) yields km of credits. Then the coefficient on all techs should be the specified fraction. However, this does not work because the demand for credits is far exceeded by the supply of credits.

The closest I've gotten this to working is to maintain the output-ratio I just described and then multiply the vehicles' coefficients (from the original transportation file) by the target BEV share. However, this isn't producing quite right results, though it gets somewhat near (+/- 10%) the correct value. 

Any thoughts on what the missing piece might be?

**Comment by pkyle** [comment]
Send me what you've got! And, sorry for anything I suggested that was a dead end. The unit conversions sure do make things confusing, but ultimately what we're aiming for here is for the BEVs and FCEVs to produce 1 credit, all others to produce 0, and for all technologies to consume X credits per unit output, where X is the portion of vehicles that are required to be electric or hydrogen.

**Comment by robbieorvis** [comment]
Just an update here... I finally got this to work.

The combination that worked for me was:

output-ratio = 1E-6 for all qualifying technologies
pMultiplier = 1E9 for all qualifying technologies
coefficient = Target ZEV Share [%] / 1.055 (this is the btu to MJ conversion factor) * 1E3 * load factor

Because a ZEV standard is a sales standard, you have to make a new credit for each 5 year increment applied only to the vehicles sold in that year. A separate standard is also needed for each vehicle type in each region. So for example you might have an EU12 Compact Car 2025 ZEV Credit, EU12 Subcompact Car 2025 ZEV Credit, EU12 2030 Compact Car ZEV Credit, EU12 Subcompact Car 2030 ZEV Credit, and so on.

Finally, a critical step is to create a new query that omits the ZEV credits when calculating transport service output.
