### ISSUE TITLE
Setting up GCAM on cluster computer

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#55]
Hi 
I need assistance setting up  and installing  GCAM 4.3 on a CentOS computing cluster.
Any available tutorials or help will be greatly appreciated.  
Thank you.

**Comment by pralitp** [comment]
The documentation for building GCAM should cover this:
http://jgcri.github.io/gcam-doc/gcam-build.html

You will need to ensure the third party libraries listed there are available on your cluster or compile them yourself.  You can then use the instructions for compiling with the generic Makefile.
