### ISSUE TITLE
Policy Cost not reported

### ISSUE THREAD

**Issue by fkanyako** [JGCRI/gcam-core#56]
Hi,
I added new technology to GCAM 4.4 (fixed and floating offshore wind) and change the capital cost of Onshore Wind. My data start from the year 2015 to 2100. From 1975 to 1990, I use default GCAM values for onshore. For offshore fixed and floating wind, I used some dummy values from the literature.
The simulation for BAU works fine except it does not calibrate in 2005 and 2010.  From 2015 to 2100 it works fine and the result is acceptable. 
When I implement a policy (RCP 2p6), I observe the same thing, 2005 and 2010 doesn't calibrate in every "Policy Target Runner: scenario dispatch ", 2015 to 2100 works well, however, the simulation does not report policy cost at the end of the simulation. 

Is this because 2005 and 2010 do not calibrate? If yes, how do I fix it?
I could maybe turn off offshore wind entirely for the years 1990 to 2010 and it will be available in 2015. Among the electricity csv files in GCAM 4.4 (L223), how do I turn off offshore wind for 1975 to 2010?

Here is the error below:
Period 1: 1990
Model solved normally. Iterations period 1: 1. Total iterations: 24512
Fri Mar 29 19:45:19 2019:WARNING:printLogHeader: hector version 1.1

Period 2: 2005
Calibration failed by 1.4  % Technology: natural gas        Region: EU-15          Sector: gas processing Subsector: natural gas  Output: 15.74    Calibration: 15.97    relativeDiff: 0.01435  SectorOutput: 15.92    SectorShare: 1.003   
Calibration failed by 5.6  % Technology: coal (conv pul)    Region: EU-15          Sector: electricity  Subsector: coal         Output: 2.486    Calibration: 2.633    relativeDiff: 0.05556  SectorOutput: 9.555    SectorShare: 0.2755  
Calibration failed by 5.6  % Technology: Gen_II_LWR         Region: EU-15          Sector: electricity  Subsector: nuclear      Output: 3.063    Calibration: 3.244    relativeDiff: 0.05556  SectorOutput: 9.555    SectorShare: 0.3395  
Calibration failed by 2.2  % Technology: coal (conv pul)    Region: India          Sector: electricity  Subsector: coal         Output: 1.662    Calibration: 1.699    relativeDiff: 0.02166  SectorOutput: 2.514    SectorShare: 0.6759  
Model did not calibrate successfully in period 2
ERROR:Model did not solve period 2 within set iteration 504
ERROR:Currently Unsolved Markets: 
ERROR:Unsolved Part 1: Solvable Markets
ERROR:X,         XL,        XR,        ED,        EDL,       EDR,       RED,       brk, Supply,    Demand,    Mrk Type,  Market,                             
ERROR:Unsolved Part 2: Unsolvable Markets Not Cleared
ERROR:X,         XL,        XR,        ED,        EDL,       EDR,       RED,       brk, Supply,    Demand,    Mrk Type,  Market,                             
ERROR:0.438     , 0.438     , 0.438     , -0.814566 , -0.814566 , -0.814566 , 0.0065931 ,	0  , 124.363   , 123.548   , Normal    , globalcoal                          , 
ERROR:0.98      , 0.98      , 0.98      , -0.32785  , -0.32785  , -0.32785  , 0.00332922,	0  , 98.8043   , 98.4764   , Normal    , globalnatural gas                   , 
ERROR:

Period 3: 2010
Calibration failed by 1.5  % Technology: natural gas        Region: USA            Sector: gas processing Subsector: natural gas  Output: 22.63    Calibration: 22.97    relativeDiff: 0.01489  SectorOutput: 22.91    SectorShare: 1.003   
Calibration failed by 4.6  % Technology: coal (conv pul)    Region: USA            Sector: electricity  Subsector: coal         Output: 6.778    Calibration: 7.105    relativeDiff: 0.04608  SectorOutput: 15.14    SectorShare: 0.4695  
Calibration failed by 1.8  % Technology: gas (steam/CT)     Region: Africa_Northern Sector: electricity  Subsector: gas          Output: 0.5428   Calibration: 0.5529   relativeDiff: 0.01826  SectorOutput: 0.9447   SectorShare: 0.5853  
Calibration failed by 1.5  % Technology: natural gas        Region: Australia_NZ   Sector: gas processing Subsector: natural gas  Output: 1.348    Calibration: 1.369    relativeDiff: 0.01522  SectorOutput: 1.362    SectorShare: 1.005   
Calibration failed by 5    % Technology: coal (conv pul)    Region: Australia_NZ   Sector: electricity  Subsector: coal         Output: 0.6226   Calibration: 0.6555   relativeDiff: 0.05024  SectorOutput: 1.009    SectorShare: 0.6494  
Calibration failed by 1.1  % Technology: natural gas        Region: Brazil         Sector: gas processing Subsector: natural gas  Output: 0.9526   Calibration: 0.9634   relativeDiff: 0.01129  SectorOutput: 0.9526   SectorShare: 1.011   
Calibration failed by 1.2  % Technology: natural gas        Region: Canada         Sector: gas processing Subsector: natural gas  Output: 2.875    Calibration: 2.91     relativeDiff: 0.0121   SectorOutput: 2.883    SectorShare: 1.01    
Calibration failed by 6.9  % Technology: coal (conv pul)    Region: Canada         Sector: electricity  Subsector: coal         Output: 0.2946   Calibration: 0.3166   relativeDiff: 0.06946  SectorOutput: 2.188    SectorShare: 0.1447  
Calibration failed by 6.9  % Technology: Gen_II_LWR         Region: Canada         Sector: electricity  Subsector: nuclear      Output: 0.3037   Calibration: 0.3264   relativeDiff: 0.06946  SectorOutput: 2.188    SectorShare: 0.1492  
Calibration failed by 2.5  % Technology: coal (conv pul)    Region: China          Sector: electricity  Subsector: coal         Output: 11.57    Calibration: 11.87    relativeDiff: 0.0247   SectorOutput: 15.29    SectorShare: 0.7763  
Calibration failed by 2    % Technology: coal (conv pul)    Region: EU-12          Sector: electricity  Subsector: coal         Output: 0.8677   Calibration: 0.8857   relativeDiff: 0.02033  SectorOutput: 1.586    SectorShare: 0.5585  
Calibration failed by 3.9  % Technology: coal               Region: EU-12          Sector: district heat Subsector: coal         Output: 0.1323   Calibration: 0.1273   relativeDiff: 0.03948  SectorOutput: 0.2789   SectorShare: 0.4563  
Calibration failed by 3.9  % Technology: gas                Region: EU-12          Sector: district heat Subsector: gas          Output: 0.114    Calibration: 0.1097   relativeDiff: 0.03948  SectorOutput: 0.2789   SectorShare: 0.3932  
Calibration failed by 3.3  % Technology: natural gas        Region: EU-15          Sector: gas processing Subsector: natural gas  Output: 15.7     Calibration: 16.24    relativeDiff: 0.03334  SectorOutput: 16.13    SectorShare: 1.007   
Calibration failed by 11   % Technology: coal (conv pul)    Region: EU-15          Sector: electricity  Subsector: coal         Output: 1.91     Calibration: 2.145    relativeDiff: 0.1097   SectorOutput: 9.652    SectorShare: 0.2222  
Calibration failed by 11   % Technology: gas (steam/CT)     Region: EU-15          Sector: electricity  Subsector: gas          Output: 1.03     Calibration: 1.157    relativeDiff: 0.1097   SectorOutput: 9.652    SectorShare: 0.1199  
Calibration failed by 11   % Technology: gas (CC)           Region: EU-15          Sector: electricity  Subsector: gas          Output: 1        Calibration: 1.124    relativeDiff: 0.1097   SectorOutput: 9.652    SectorShare: 0.1164  
Calibration failed by 11   % Technology: Gen_II_LWR         Region: EU-15          Sector: electricity  Subsector: nuclear      Output: 2.647    Calibration: 2.973    relativeDiff: 0.1097   SectorOutput: 9.652    SectorShare: 0.308   
Calibration failed by 1.3  % Technology: natural gas        Region: Europe_Non_EU  Sector: gas processing Subsector: natural gas  Output: 1.495    Calibration: 1.514    relativeDiff: 0.01301  SectorOutput: 1.498    SectorShare: 1.011   
Calibration failed by 3.2  % Technology: gas                Region: Europe_Non_EU  Sector: district heat Subsector: gas          Output: 0.02121  Calibration: 0.02056  relativeDiff: 0.03161  SectorOutput: 0.0398   SectorShare: 0.5167  
Calibration failed by 2.2  % Technology: natural gas        Region: India          Sector: gas processing Subsector: natural gas  Output: 2.157    Calibration: 2.206    relativeDiff: 0.02223  SectorOutput: 2.158    SectorShare: 1.022   
Calibration failed by 4.5  % Technology: coal (conv pul)    Region: India          Sector: electricity  Subsector: coal         Output: 2.245    Calibration: 2.351    relativeDiff: 0.04498  SectorOutput: 3.456    SectorShare: 0.6803  
Model did not calibrate successfully in period 3
ERROR:Model did not solve period 3 within set iteration 506
ERROR:Currently Unsolved Markets: 
ERROR:Unsolved Part 1: Solvable Markets
ERROR:X,         XL,        XR,        ED,        EDL,       EDR,       RED,       brk, Supply,    Demand,    Mrk Type,  Market,                             
ERROR:Unsolved Part 2: Unsolvable Markets Not Cleared
ERROR:X,         XL,        XR,        ED,        EDL,       EDR,       RED,       brk, Supply,    Demand,    Mrk Type,  Market,                             
ERROR:0.5       , 0.5       , 0.5       , -3.00848  , -3.00848  , -3.00848  , 0.0214505 ,	0  , 143.261   , 140.252   , Normal    , globalcoal                          , 
ERROR:1.5       , 1.5       , 1.5       , -1.11737  , -1.11737  , -1.11737  , 0.00991202,	0  , 113.846   , 112.729   , Normal    , globalnatural gas                   , 
ERROR:

Period 4: 2015
Model solved normally. Iterations period 4: 1. Total iterations: 25522

**Comment by pralitp** [comment]
Indeed, GCAM will skip the policy cost calculation if any of the periods in the base scenario run fail to solve.

We will have to fix the underlying issue with regards to why it doesn't solve / calibrate 2005 and 2010.  Given your intent was not to change the historical years in the first place I would suggest looking at the model results in 2005 and 2010, mostly likely electricity generation by technology in any of the regions listed above, comparing a scenario which does calibrate successfully and your scenario that does not.

I suspect that you will find something along the lines of a technology which should have been active only in future model years was also active in the historical years.  Thus throwing off the calibration of the other technologies.
