### ISSUE TITLE
GCAM Queries of Same Outputs with Different Aggregations Producing Different Results

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#57]
Hello,

In comparing some of the outputs from GCAM using the model interface, I noted that in certain aggregations of outputs, GCAM produces inconsistent results. Specifically, GCAM produces different results when running the "nonCO2 emissions by region" query versus the "nonCO2 emissions by subsector" or "nonCO2 emissions by sector" queries, which produce identical results to one another.

The issue appears to be limited to nonCO2 gases and is most pronounced with methane. Methane emissions are about 2.75 times higher when using the regional aggregation than with either the sector or subsector aggregations.

For example, when running the reference scenario, I get 231 Tg CH4 when summing all regions using the "nonCO2 emissoins by region" but 84.6 Tg when summing all regions using "nonCO2 emissions by subsector" and "nonCO2 emissions by sector" queries.

In addition to identifying why this is happening, it would be great to know which of these is the "correct" set of values to use.

Thank you.

**Comment by pkyle** [comment]
The queries for nonCO2 emissions by sectors, subsectors, and technologies don't pick up emissions from fossil resource production, which need to be queried separately and added post hoc. The name of the query is `nonCO2 emissions by resource production`

**Comment by robbieorvis** [comment]
Got it thank you. That makes perfect sense and explains why the biggest discrepancy was with methane.
