### ISSUE TITLE
Debugging/Assessing Which Markets Don't Clear and Why

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#58]
Hello,

I'm running some scenarios using the res and policy-portfolio-standard policies and am running into an issue where subtle changes in policy settings push some of the markets into not being able to clear.

Does anyone have advice on how to debug this or why an RPS-like policy would result in markets not clearing? I assume one reason is if resource constraints are maxed out, but I believe my current setup should allow for switching between technology types when that happens.

I'm currently testing a 15% RPS in the US (using GCAM global) including several technologies.

Thanks.

**Comment by robbieorvis** [comment]
A follow-up note: I determined that the RPS policy (as designed/discussed by rplevin separately) and accompanying markets may not clear when certain resource types are flagged and the RPS value is set above a certain level. I believe this has to do with the fact that some resource types (geothermal and biomass, for example) quickly run out of the resource potential, which in turn prevents the market from clearing.

**Comment by pralitp** [comment]
@robbieorvis, understanding a policy (especially an RPS policy) does not solve can be pretty difficult.  Often it ends up being some subtle detail that throws things off such as forgetting to tag a technology or not getting all of the vintages.  Without seeing your implementation it is hard to make any specific recommendations.

Although, a technique that I have found to be quite useful in debugging is to use a feature @rjplevin added in GCAM 5.1 where you can get GCAM to generate supply/demand curves for the markets and price points of your choosing.  You can find an example input file in `input/extra/supply_demand_curves.xml` which can be added in the `<ScenarioComponents>` section of your configuration just like any other add on file.  Results will be written, by default, into `exe/supplyDemandCurves.csv`
I have set up this file to choose my policy market and perhaps a few of the markets that I consistently do not solve when the policy is active.  Note, I also suggest adding more price points with in the range to have more density and perhaps catch some discontinuous behaviors if they exist, maybe 0.7 to 1.3 every 0.025.
Using this technique you could verify your policy behaves as you expect.  We would like to see the supply and/or demand (depending on what type of policy we are talking about) is smooth and does not asymptote above/below where some potential solution may be. It could also show, for instance if there really is some structural issue by including some resource types that prevent solution.

**Comment by Arlo23RS** [comment]
Hi @pralitp 

I am having some issues getting GCAM7.1 to output the supply as demand curves using the method you described above. 

The error i get is Unknown tag: supply-demand-curve-saver error and the csv never gets written out.

Any advise or idea of what I am missing. I also set the write output to 1 under "supplyDemandOutputFileName". 

Any help is greatly appreciated. 

Thank you.
