### ISSUE TITLE
Forcing target in policy target runner

### ISSUE THREAD

**Issue by melgeorgev** [JGCRI/gcam-core#59]
Hello,

Am a PhD student at the UMd Policy School. Was trying to run the off-the-shelf GCAM 5.1 for SSPs 1-5 with the provided target finder files. I noticed that GCAM uses 2p0 as the radiative forcing target. I would have expected 1p9 to match with a 1.5 deg C mean temperature rise. Is there a specific reason for choosing 2p0 and not 1p9?
Thanks!
[Policy target runner.txt](https://github.com/JGCRI/gcam-core/files/3108232/Policy.target.runner.txt)

**Comment by kvcalvin** [comment]
The targets in those files were set to ensure that radiative forcing in MAGICC6 (which was run offline) matched 1.9 W/m2. This resulted in slight differences between the target specified in target finder (which Hector will match) and the 1.9 W/m2 target. We will likely update the target runner targets in the future as matching the MAGICC6 values are no longer a goal.
