### ISSUE TITLE
Rename Release/objects to gcam.exe on Mac

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/gcam-core#6]
Consider renaming exe/Release/objects to exe/gcam.exe since this is (i) more obvious and (ii) consistent with the Windows and Linux platforms. Consistency is helpful for 3rd party developers like me! ;~)

**Comment by kvcalvin** [comment]
Closing this one since it is duplicative of https://github.com/JGCRI/gcam-core/issues/27
