### ISSUE TITLE
debug file

### ISSUE THREAD

**Issue by jayfuhrman** [JGCRI/gcam-core#60]
I'm running gcam 5.1.3 on a windows PC to do quick single test runs, and it doesn't seem to be creating the debug.xml file, or the gas.emk file, even though "write-output" for both of these files is set to 1.  Is there somewhere else I need to change in the configuration file to get these files to be created?  

When I run on my school's cluster, these files are created, and as far as I can tell the default config files are the same.

**Comment by pralitp** [comment]
With regards to `debug.xml` it should be created.  It does attempt to include the scenario name in the file name by default so maybe if there was something in the resulting filename that was illegal it would not get created.

The `gas.emk` is generated by the `MAGICC` climate model only.  So if you are not running that, and `hector` is the default then it would not be generated.  Note that the `hector` main output gets stashed away in `exe/logs/gcam-hector-outputstream.csv`.

**Comment by pkyle** [comment]
Note also that when running in `BatchMode`, there is no `debug[ScenarioName].xml` file created.
