### ISSUE TITLE
How to turn off an Energy Technology in the Energy Sector in GCAM 4.4

### ISSUE THREAD

**Issue by fkanyako** [JGCRI/gcam-core#63]
Hi,
I am using GCAM 4.4, I want to know how to turn off a particular energy technology in GCAM 4.4. For example, let's say I want to run the model without Onshore wind or Solar or Nuclear energy.

Could you please tell me how do this GCAM 4.4? I understand I need to edit some CSV files, then generate new XML input, but am not too confident which specific CSV files I need to edit among the "L223" CVS files.  

Many thanks
Franklyn

**Comment by pkyle** [comment]
The best way to do this is through the "share-weight" parameter, which is set in the following files in input/gcam-data-system/energy-data/assumptions:
```
A23.subsector_shrwt.csv
A23.globaltech_shrwt.csv
A23.subsector_interp.csv
A23.globaltech_interp.csv
```
Note that the share-weights from an interpolation rule will over-ride the share-weights set by each year in one of the `*_shrwt` tables. Also don't try to shut off any technologies in the calibration years. Just do this in whatever future years you want for new builds to stop coming in.
If you don't want capital stock carryover (i.e., technologies built prior to 2010 continuing to produce electricity decades into the future), you'll need to change the retirement assumptions in A23.globaltech_retirement.csv.
