### ISSUE TITLE
Query "refined liquids production by tech (new)" does not retrieve data in 2100 for China

### ISSUE THREAD

**Issue by SRSantosdaSilva** [JGCRI/gcam-core#64]
Hi,

Does anyone know what is the difference between the queries "refined liquids production by tech (new)" and "refined liquids production by tech"? They lead to different outputs.

 In addition, if you run "refined liquids production by tech (new)" for China, results only go to 2095.

Thanks.

**Comment by SRSantosdaSilva** [comment]
I ran the query "refined liquids production by tech (new)" for other two databases and I did not see the issue with the results in China. 

Then it is not making much sense why in the first database I had the issue for China (plus 3 other regions) while all other regions were fine. Anyway, it seems something specific for that database.  

But if anyone could tell the difference between the queries "refined liquids production by tech (new)" and "refined liquids production by tech", I would greatly appreciate it.

Thank you very much.

**Comment by pkyle** [comment]
The "new" query reports only the output from the new investment in the given time period. For example, the values reported in the year 2020 reflect the output of refineries installed between 2016 and 2020. The refinery lifetimes and retirement curves are set in`input/gcamdata/inst/extdata/energy/A22.globaltech_retirement.csv`. The functional form for the s-curve retirement function is described and implemented in the last few lines of `cvs/objects/technologies/source/s_curve_shutdown_decider.cpp`
Re: China, I haven't looked into it specifically but there is a declining population, and there are assumed efficiency improvements, from 2095-2100, so I'd imagine that there is simply no refinery capacity expansion between 2096 and 2100.
