### ISSUE TITLE
Files 2025_target_finder.xml and 2040_target_finder.xml

### ISSUE THREAD

**Issue by SRSantosdaSilva** [JGCRI/gcam-core#66]
Could anyone please explain what is the purpose of the files 2025_target_finder.xml and 2040_target_finder.xml located in the folder input/policy and how to set up a run with them?

Thank you very much in advance.

**Comment by pralitp** [comment]
Those files are used to create some of the "shared policy assumptions" (SPA) in some of the SSP policy scenarios.  For instance you will notice `2025_target_finder.xml` is referenced in `batch_SSP_SPA1.xml` and you could use as a guide on how to use it.
The idea behind these files is that some regions may have region specific policies of varying ambition up to some year, such as 2025 or 2040, as the scenario design calls for.  And after that model year they will all join together into a single market which the target finder algorithm will then use to ensure they meet the desired climate target.

To get into some specifics in case it is helpful:  To get such a set up we will create 3 `CO2` markets:
* CO2_NearTerm: The regional near term policy (such as in `input/policy/spa14_tax.xml`)
* CO2_tf: The market the target finder algorithm will change to achieve it's climate target (such as in `input/policy/policy_target_2p0_spa1.xml`)
* CO2: The market all of the technologies in the model will be looking at to determine costs.  We use the "linked GHG markets" to make the CO2 market point to either `CO2_NearTerm` or `CO2_tf` depending on the model year (this is what is done in `input/policy/2025_target_finder.xml`):

```
         <linked-ghg-policy name="CO2_NearTerm_Link">
            <price-adjust fillout="1" year="1975">1</price-adjust>
            <demand-adjust fillout="1" year="1975">1</demand-adjust>
            **<policy-name>CO2</policy-name><market>USA</market>
            <linked-policy>CO2_NearTerm</linked-policy>**
            <price-unit>1990$/tC</price-unit>
            <output-unit>MtC</output-unit>
            **<start-year>1975</start-year>**
         </linked-ghg-policy>
         <linked-ghg-policy name="CO2_LongTerm_Link">
            <price-adjust fillout="1" year="1975">1</price-adjust>
            <demand-adjust fillout="1" year="1975">1</demand-adjust>
            **<policy-name>CO2</policy-name><market>USA</market>
            <linked-policy>CO2_tf</linked-policy>**
            <price-unit>1990$/tC</price-unit>
            <output-unit>MtC</output-unit>
            **<start-year>2025</start-year>**
         </linked-ghg-policy>
```
