### ISSUE TITLE
SSP batch_SSP_SPA23 batch_SSP_SPA4 not able to run using standard files

### ISSUE THREAD

**Issue by nancybrett** [JGCRI/gcam-core#67]
Hi
Using the delivered SSP batch files, the model is failing in all SSPs except SPA1.
SPA5 returns error regarding land allocation
SPA23 fails due to an error with MACC_TC_SSP2 file.  

Did not create node Root_Tuber_RioGrande as the nocreate input flag was set.
	at AgSupplySubsector name = Root_Tuber_RioGrande, nocreate = 1
	at AgSupplySector name = Root_Tuber, nocreate = 1
	at region name = USA
	at world 
	at scenario 
	in file:///Users/nancyreneebrett/Downloads/gcam-v5.1.3-Mac-Release-Package/input/gcamdata/xml/MACC_TC_SSP2.xml
Did not create node Root_Tuber_TennR as the nocreate input flag was set.

**Should these scenario batch files be able to run?  As noted, running SPA1 runs fine.**

<img width="919" alt="Screenshot 2019-07-13 at 09 25 10" src="https://user-images.githubusercontent.com/48177479/61168563-5b587000-a550-11e9-83c0-6f0c8bab540f.png">
<img width="1192" alt="Screenshot 2019-07-13 at 09 31 42" src="https://user-images.githubusercontent.com/48177479/61168611-0f59fb00-a551-11e9-82b2-85d74cefedc7.png">

**Comment by pralitp** [comment]
I suspect this is similar to #44.  When running any of the SSP batch XML files you will need to make sure you start with a `configuration.xml` that has a completely empty `<ScenarioComponents></ScenarioComponents>` section.

**Comment by nancybrett** [comment]
Thank you! That worked!
