### ISSUE TITLE
Document creation of policies in XML

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/gcam-core#7]
It would super helpful to the user community if JGCRI would post documented examples of common policy implementations to the GCAM Wiki. In my view, this is a critical gap in user documentation.

Examples could include:
- Air pollutant taxes or caps
- GHG taxes or caps
- CAFE standard
- Renewable Electricity Standard
- Technology subsidies
- Forced technology penetration
- High-efficiency technology end-use requirements
- Fuel carbon intensity policy

**Comment by djtrainwreckx** [comment]
I would love to see these materials
-Osman

**Comment by rplzzz** [comment]
The GCAM documentation has its own repository.  If you could open an issue  in the [gcam-doc issue tracker](https://github.com/JGCRI/gcam-doc/issues), that would help us keep better track of gaps in the documentation.
