### ISSUE TITLE
Question: Access to Configuration file used during a run

### ISSUE THREAD

**Issue by nancybrett** [JGCRI/gcam-core#70]
Hello
I have a question.  Is it possible to see the configuration file,  or the configurable inputs, which were used for any particular database write? It is sometimes helpful to double check inputs used when looking back.

BR Nancy

**Comment by pralitp** [comment]
We've thought about setting up such a structure to be able to trace back results in a database to the configuration used and potentially even more detailed information about the source of the results.

However, unfortunately at this time there is no way to trace database outputs back to configuration / inputs at all.
