### ISSUE TITLE
Reference scenario projects negative LUC emissions in 2015

### ISSUE THREAD

**Issue by jayfuhrman** [JGCRI/gcam-core#75]
Hi all,

The reference scenario for GCAM 5.1.3 projects that LUC emissions go negative in 2015 (query: LUC emissions by region, global), indicating a complete stoppage to and reversal of deforestation.  Removing land protection and replacing the ag_prodchange_ref_IRR_MGMT input file with the included SSP3 or 4 versions seems to at least help get the sign correct but is still outside the uncertainty bounds on LUC emissions from the 2018 Global Carbon Budget (Le Quéré et al) 

Is this an issue anyone else has encountered / any suggestions on how to resolve this?

![emissions-diagnostics](https://user-images.githubusercontent.com/48569483/64883162-bc71f200-d62c-11e9-9c31-46692f1e113a.png)

![image002](https://user-images.githubusercontent.com/48569483/64882758-c515f880-d62b-11e9-9a9c-028376361a60.png)

**Comment by kvcalvin** [comment]
This is a known issue. We don't have a correction yet, but are hoping to for the next release.

**Comment by kvcalvin** [comment]
We have corrected this in GCAM v5.2. LUC emissions are now positive in 2015.
