### ISSUE TITLE
GCAM-USA target finder failing to calibrate in 2010

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#76]
Hello,

I'm trying to do a GCAM run using GCAM-USA and a target-finder using a 2 degree temperature target. I'm using GCAM v5.1.3

On scenario dispatch #1 (second run), I'm getting an error that the model is failing to calibrate starting in 2010.

The first tax year is 2020, so not sure why this is happening.

Files attached.
[2_Degree.zip](https://github.com/JGCRI/gcam-core/files/3745425/2_Degree.zip)

**Comment by robbieorvis** [comment]
Just to follow-up, the calibration fails for the US states, so it appears this is an issue running target-finder with GCAM-USA. 

Any help would be much appreciated.

**Comment by gokuliyer** [comment]
Hi @robbieorvis 

GCAM-USA is not yet equipped to do target finder as the model does not include non-CO2s for the time being. This is work in progress.

**Comment by robbieorvis** [comment]
Okay, thanks.
