### ISSUE TITLE
Levelized costs of electricity via GCAM v5.1.3 

### ISSUE THREAD

**Issue by IMA18** [JGCRI/gcam-core#77]
Attached you will find the Levelized Cost of Electricity (LCOE) for every technology, region and SSP. These costs were obtained by running GCAM v5.1.3 Windows release package for every SSP and reference scenario. I found some discrepancies with the LCOE of biomass with CCS, coal with CCS and natural gas with CCS for all regions and CSP in OECD only. I have corrected these costs as follows:

•	LCOE of biomass with CCS in 2100 needs to be divided by 1000.
•	LCOE of coal with CCS in 2100  needs to be divided by 1000.
•	LCOE of natural gas with CCS in 2100  needs to be divided by 1000.
•	LCOE of CSP in 2100  in OECD regions only needs to be divided by 100.

Can you please confirm that what I am doing to correct these LCOE data is correct?

Looking forward to your feedback.

Best,

Ibrahim
[GCAM_LCOE_data.xlsx](https://github.com/JGCRI/gcam-core/files/3805607/GCAM_LCOE_data.xlsx)

**Comment by pkyle** [comment]
Ibrahim,
The CCS technologies have high reported costs in order to prevent them from coming in, something like $10,000 added when there is zero carbon price, in order to avoid them being allocated market share by the logit sharing formulation.
CSP in the "European Free Trade Association" region (Switzerland, Iceland, and Norway) has the costs it does because these nations have insufficient solar resource to produce power by this technology. Unlike in the case of CCS, here the high costs are based on data on "direct normal irradiance", but the effect is similar as the capacity factors are so low that the LCOEs are orders of magnitude higher than any other technologies.

**Comment by IMA18** [comment]
Thank you for your prompt response. 

I think its is much more than $10,000. Is there any easy way to get the real LCOE for technologies with CCS excluding the added amount? For example, is there any predefined scenario in the exe file that does not prevent technologies with CCS so that I can get the actual LCOE in 2100?

Thanks. Ibrahim

**Comment by pkyle** [comment]
The easiest way would just be to read in a small carbon price. When the carbon price is zero the specific costs written out are not meaningful, but the code that applies the cost adder does not do anything when there is a non-zero carbon price. There are some policy files in the `input/policy` folder that can be adapted. E.g. `carbon_tax_10_5.xml`; just re-set all of the carbon prices to some low number like 0.01 or 0.1.

**Comment by IMA18** [comment]
Thank you for your help.

Ibrahim

**Comment by IMA18** [comment]
Hi, 

I apologize for opening this issue again, but I am still trying to get the real LCOE of technologies with CCS in 2100 without the cost adder.

Following your recommendation, I made three changes on the global reference configuration file and policy file.
1. I changed <Value name="policy-target-file">../input/policy/**forcing_target_4p5**.xml</Value> to <Value name="policy-target-file">../input/policy/**carbon_tax_10_5**.xml</Value>

2. I set the find-path option to 1. Value name="find-path">**1**</Value>

3. I changed the tax to 0.01 and applied it to all regions, i.e., not only the US.

When I ran GCAM, I got the following error message: 
Starting new scenario: Reference
Tue Nov 12 17:32:16 2019:WARNING:Hector::Logger::printLogHeader: hector version 2.0
Tue Nov 12 17:32:16 2019:WARNING:Hector::Logger::printLogHeader: hector version 2.0
Tue Nov 12 17:32:16 2019:WARNING:Hector::Logger::printLogHeader: hector version 2.0
**Using negative-emissions-final-demand wth target-finder without explicitly creating a market for CO2 may hinder solution performance.**
Please read in a policy file with a zero tax.
Caloutput read in but no land read in for technology Middle East Corn_ArabianSea_RFD_hi
Caloutput read in but no land read in for technology Middle East Corn_ArabianSea_RFD_lo
Reading advanced target finder configuration file ../input/policy/carbon_tax_10_5.xml
**Unrecognized string: world found while parsing policy-target-runner.
Must read in a target value for the policy.**

I have attached to this comment the configuration file and policy file too.
[configuration.txt](https://github.com/JGCRI/gcam-core/files/3837421/configuration.txt)
[carbon_tax_10_5.txt](https://github.com/JGCRI/gcam-core/files/3837423/carbon_tax_10_5.txt)


Thank you for your time.
Ibrahim
