### ISSUE TITLE
Compiling GCAM 5.2 cannot find hector headers folder

### ISSUE THREAD

**Issue by jayfuhrman** [JGCRI/gcam-core#80]
When attempting to compile v 5.2 on linux cluster, it gets part-way through the build process before throwing the following error:

**In file included from world.cpp(72):
../../climate/include/hector_model.hpp(55): catastrophic error: cannot open source file "climate/source/hector/headers/core/core.hpp"
#include "climate/source/hector/headers/core/core.hpp"
^

compilation aborted for world.cpp (code 4)**

This appears to be because the cvs/objects/climate/source/hector/headers folder is missing from the separate hector source code download. 

Have there been any changes made to hector since the previous release? If not, copying the headers folder over from the working version I had from v5.1.3 (after newly-downloading hector the latest hector source code) seems to resolve the issue so that it at least gets through the build process.

**Comment by rplzzz** [comment]
@jayfuhrman, try running `git submodule update --init cvs/objects/climate/source/hector` from the top level of the cloned repository.  That should get you teh correct version of Hector.

**Comment by jayfuhrman** [comment]
This doesn't seem to work because I didn't clone from github, I just downloaded the tar.gz files for the latest releases of both hector and gcam.  The source directory doesn't seem to exist in v 2.3.0 of hector - is this instead called "src" now?

**Comment by jayfuhrman** [comment]
The error seems to occur when it cannot find the hector/headers directory, which is not in the tar file for the latest release

**Comment by rplzzz** [comment]
The hector repository underwent some reorganization recently so as to make it compatible with Rcpp, but GCAM is still using a version from prior to that change.

It appears there is no easy way to include submodules in a release package generated from github.   At this point, the quickest way forward for you would be to download the [Hector v2.0 release](https://github.com/JGCRI/hector/releases/tag/v2.0.0) and untar it in the `cvs/objects/climate/source/hector` subdirectory.  

@JGCRI/gcam-dev It looks like we will need to manually add the hector distribution to the release package.  Any volunteers?

**Comment by pralitp** [comment]
To be clear the release package does not include any of the C++ source.  And given hector is a submodule I do not believe it is possible to have Github include in the source download.

Note, in principal the documentation is correct: http://jgcri.github.io/gcam-doc/gcam-build.html#3-compiling-hector

However someone deleted the `gcam-integration` branch on the hector repository so the link is dead.  I'll re-create the branch so the link works again and cross my fingers the branch doesn't get depleted again.

**Comment by ashiklom** [comment]
> I'll re-create the branch so the link works again and cross my fingers the branch doesn't get depleted again.

Would it be a good idea to make that a [protected branch](https://help.github.com/en/github/administering-a-repository/about-protected-branches#branch-protection-settings) on GitHub?
