### ISSUE TITLE
The database folder 

### ISSUE THREAD

**Issue by sshreekar** [JGCRI/gcam-core#81]
Hey, I am running 5.2 GCAM in cluster. I just migrated to the 5.2 version. Also, I kept my configuration file and batchfiles as I had before. When the model solved but I am getting the following error and the batch queries were not processed.

All model periods solved correctly.
Model run completed.
ERROR:Failed due to invalid trial price generated by solver.
Printing output
Starting output to XML Database.
Model run completed.
Model exiting successfully.

**Comment by pralitp** [comment]
> I kept my configuration file and batchfiles as I had before

You should not assume that configurations and batch files are compatible between different versions of GCAM.  At the very least you should compare what has changed between the different versions of GCAM in the configuration file, for instance, and update your files accordingly (in addition custom XML add-on files and queries should be checked as well).

Could you run with the `configuration_ref.xml` that came with the `5.2` release and verify your database output works then?  There were no changes to the XML database output components in GCAM 5.2.

**Comment by sshreekar** [comment]
I can see that the model on completion generates the database folder as it should. However, the error I reported earlier still does appear at the end of the model solution at the end of the log files. I am running the model in the target finder mode with forcing 2p6 scenario. I am using the configuration files that came with the 5.2 version (both the 2p6 scenario and carbon tax files). There are no other changes in this configuration setup.

**Comment by sshreekar** [comment]
Surprisingly, as the model, under the target finder mode, completes the Scenario dispatch #3, The model solution ends with above message. The error shows up in the log file. I tried different cases, and the error is the same in each case. Does the new version have issue with running the model under the target finder mode?

**Comment by pralitp** [comment]
Did you start with `configuration_policy.xml`?  In GCAM 5.2 we have moved to a near-term/long-term policy (where target finder is long-term) and starting from the configuration will help ensure the markets get set up correctly.

**Comment by sshreekar** [comment]
So, for the target finder, these lines should be commented right?
 		<Value name = "near-term-co2">../input/policy/spa14_tax.xml</Value>
		<Value name = "co2-link">../input/policy/2025_target_finder.xml</Value>

**Comment by pralitp** [comment]
I'm not sure what you mean by commented but for target finder you definitely need these three `ScenarioComponents` in your configuration:
```
<Value name = "long-term-co2">../input/policy/carbon_tax_0.xml</Value>
<Value name = "near-term-co2">../input/policy/spa14_tax.xml</Value>
<Value name = "co2-link">../input/policy/2025_target_finder.xml</Value>
```

**Comment by sshreekar** [comment]
I am sorry being naive here but I am not clear what these last two xml files will do. The carbon_tax_0 file defines the market for CO2, I get that. Is there anywhere I could find some more information about these last two xml files?

**Comment by sshreekar** [comment]
For example, just to clarify here, along with other files, these files are being read in configuration file.

Parsing ../input/gcamdata/xml/liquids_limits.xml scenario component.
Parsing ../input/gcamdata/xml/water_elec_liquids_limits.xml scenario component.
Parsing ../input/gcamdata/xml/negative_emissions_budget_gSSP2.xml scenario component.
Parsing ../input/solution/cal_broyden_config.xml scenario component.
Parsing ../input/policy/carbon_tax_0.xml scenario component.
XML parsing complete.
Starting new scenario: ref2p6target
Wed Nov 13 15:53:24 2019:WARNING:printLogHeader: hector version 2.0
Wed Nov 13 15:53:25 2019:WARNING:printLogHeader: hector version 2.0
Wed Nov 13 15:53:25 2019:WARNING:printLogHeader: hector version 2.0
Reading advanced target finder configuration file ../input/policy/forcing_target_2p6_overshoot.xml

Since I am running the 2p6 overshoot scenario under the target file, do I still need to add those spa14_tax.xml and 2025_target_finder.xml files?

**Comment by sshreekar** [comment]
Yes, including those two files, there is no error and the model solves and generates the database. Is there anywhere some description about these two files?
