### ISSUE TITLE
Error : 

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#84]
Hello GCAM community, 

I am running a batch file using the "trn_agg_g" and "bld_agg_g" XML file. 
I got the follow errors. 
Is this an error I should worry about? 
if yes how can I fix it this problem?

![image](https://user-images.githubusercontent.com/34580273/69662522-83092a00-1052-11ea-9f92-3451a3249e23.png)

**Comment by pkyle** [comment]
We haven't tested these "agg" sector files in a long time, but you'll need to (a) not read in the `transportation_UCD_CORE.xml` file, and (b) replace it with `transportation_agg.xml` prior to reading in the `trn_agg_*.xml` files, as the latter are just scenario-specific income elasticity assumptions. So, for each scenario there should be two transportation-related files read in.

**Comment by pkyle** [comment]
I just wanted to issue two follow-up clarifications:
1) These "aggregate" sectors are no longer supported starting in GCAM 5.2
2) My comment above only addressed transportation, but the same applies to buildings. The `bld_agg_*.xml` file (whichever you read in; should be consistent with the socioeconomic assumptions) just has income elasticity assumptions that add on to the buildings module file `building_agg.xml`. So, for each of the sectors, there should be two XML files read in.

**Comment by RawisWar** [comment]
Thank I fixed it
