### ISSUE TITLE
some problems with the output of configuration_ssp.xml with batch_SSP_SPA4

### ISSUE THREAD

**Issue by MengLuo-Sara** [JGCRI/gcam-core#85]
Hello GCAM community,

I am running a configuration_ssp.xml with  "batch_SSP_REF.xml" as "BatchFileName" in GCAM v5.2 as fellow.
![1](https://user-images.githubusercontent.com/58357330/69898480-3e082f00-1395-11ea-89e3-7dbd36783441.png)
and here is the complete configuration file
[configuration_ssp_batch_SSP_SPA4.zip](https://github.com/JGCRI/gcam-core/files/3906950/configuration_ssp_batch_SSP_SPA4.zip)
I can 
I didn't modify  other files in the model.
I can run the model 
but got the follow errors.
![2](https://user-images.githubusercontent.com/58357330/69898425-778c6a80-1394-11ea-930a-68412d2cdc9f.png)
here is the main_log file

[main_log.txt](https://github.com/JGCRI/gcam-core/files/3906961/main_log.txt)

what shoud I do to solve this problem?

**Comment by pralitp** [comment]
@MengLuo-Sara,  I think there are a couple of different things going on here.

First, from looking at your main_log I noticed that you ran ALL of the climate targets in the batch_SSP_SPA4.xml file.  We have not actually tried that in quite a while (we most typically focus on 2.6).  In addition in GCAM 5.2, with the inclusion of water markets solving has become more difficult.  So maybe on this error first I just want to verify that you were actually interested in using any of the climate targets that failed.  If so we can review some options that may help them run to completion successfully for each of them.

The second issue:  what looks to be an empty database.  Here I can notice that these `.basex` files are directly in the `output` folder and other folders that should be preset such as `queries` are now deleted.  GCAM itself will never delete your files if you had in advertantly specified a non-empty folder to write results into.  Instead you would get an error from GCAM that looks something like:
```
All model periods solved correctly.
Model run completed.
Printing output
Starting output to XML Database.
org.basex.core.BaseXException: Resource "/Users/pralitp/model/food-demand-workspace/output/queries/inf.basex (No such file or directory)" not found.
	at org.basex.core.Command.execute(Command.java:94)
	at org.basex.core.Command.execute(Command.java:116)
	at WriteLocalBaseXDB.openDB(WriteLocalBaseXDB.java:204)
	at WriteLocalBaseXDB.<init>(WriteLocalBaseXDB.java:115)
	at XMLDBDriver.<init>(XMLDBDriver.java:108)
java.io.IOException: Pipe not connected
	at java.io.PipedOutputStream.write(PipedOutputStream.java:140)
	at XMLDBDriver.receiveDataFromGCAM(XMLDBDriver.java:226)
Model run completed.
```

**HOWEVER:**  if you ask the Model Interface to `DB Open` the wrong folder, such as the `output` folder and it is not empty it will open a `WARNING` dialog stating that it **will delete your files, do you want to proceed?** and if you click yes it will delete them and replace it with an empty database.  I think that is what happened here.

Unfortunately, unless you happened to have created a back up before the files got deleted there is no way to get them back.  You will need to at the very least replace the lost contents of the `output` folder with the original from the release package however the results from the `batch_SSP_SPA4.xml` scenarios are gone.  You will need to run them again, but again you should think about which climate targets you actually want and only run them by deleting or commenting the ones you do not want such as:
```
<runner-set name="policy-target-runner">
    <!--
    <Value name="6p0">../input/policy/policy_target_6p0_spa4.xml</Value>
    <Value name="4p5">../input/policy/policy_target_4p5_spa4.xml</Value>
    <Value name="3p7">../input/policy/policy_target_3p7_spa4.xml</Value>
     -->
    <Value name="2p6">../input/policy/policy_target_2p6_spa4.xml</Value>
    <Value name="1p9">../input/policy/policy_target_1p9_spa4.xml</Value>
</runner-set>
```
