### ISSUE TITLE
GCAM with LAPACK enabled fails to build due to error in boost numeric bindings

### ISSUE THREAD

**Issue by jayfuhrman** [JGCRI/gcam-core#87]
Good afternoon,

I am attempting to build GCAM with LAPACK enabled, because @rplzzz  mentioned at the GCAM annual meeting that it might help with failures to solve.  However, I wasn't able to directly download the boost numeric bindings at the link provided in the [solver documentation](https://jgcri.github.io/gcam-doc/solver.html), so I found this version on [github](https://github.com/dilawar/boost-numeric-bindings).  

The build process seems to get most of the way through but errors out as follows:

**/home/jgf5fz/boost-numeric-bindings/boost/numeric/bindings/lapack/gesvd.hpp:79: undefined reference to `dgesvd_'
/home/jgf5fz/boost-numeric-bindings/boost/numeric/bindings/lapack/gesvd.hpp:79: undefined reference to `dgesvd_'**
make[2]: *** [gcam.exe] Error 1
make[2]: Leaving directory `/sfs/qumulo/qhome/jgf5fz/gcam-core/cvs/objects/main/source'
make[1]: *** [main_dir] Error 2
make[1]: Leaving directory `/sfs/qumulo/qhome/jgf5fz/gcam-core/cvs/objects/build/linux'
make: *** [gcam] Error 2

Would I be able to get a version of numeric bindings that works with GCAM?

Thanks!

**Comment by pralitp** [comment]
> However, I wasn't able to directly download the boost numeric bindings at the link provide

I will get this fixed in the documentation. 

With regards to the compiler error it's possible that you are getting it because it is not finding your actual LAPACK library or maybe there is some incompatibility with it. Since the missing function it is complaining about should be defined in the LAPACK library and we only indirectly call it through this numeric bindings library which is why the compiler is complaining about it there. 

Could you post the full compile command that generated the error? Also the _flavor_ of LAPACK you are using?

**Comment by jayfuhrman** [comment]
We use MKL for LAPACK. it looks like it's failing on dgesvd function, which I understand In the MKL is defined in libmkl_intel_lp64.so which is in the link line up there.

To build I have a setup file (attached) that sets up all the environment variables, which then gets called by a "makescript" as follows:


make clean

module purge
module load intel
module load intelmpi
module load boost
module load xerces
module load java

source gcam_build_LAPACK.setup
make gcam -j 8


[gcam_build_LAPACK.setup.txt](https://github.com/JGCRI/gcam-core/files/3941070/gcam_build_LAPACK.setup.txt)

**Comment by jayfuhrman** [comment]
We were able to resolve the error by adding quotation marks around the MKL environment variable options:

export MKL_CFLAGS="-fopenmp -I${MKLROOT}/include"
export MKL_LDFLAGS="-fopenmp -L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_gnu_thread -ldl -lpthread -lm"
export MKL_RPATH="-Wl,rpath,${MKLROOT}/lib/intel64"
