### ISSUE TITLE
Policy Cost By Period

### ISSUE THREAD

**Issue by fkanyako** [JGCRI/gcam-core#89]
Hi All,

Looking at policy cost output from GCAM, I understand the difference between the discounted and undiscounted policy cost.
Could someone please explain to me "policy cost by period"?

For example, I summed my output of the policy cost by period from 2020 to 2100 for USA , I expected to get the same result as the undiscounted policy cost. However, I got a totally different result. 

What are the differences between the three outputs (Discounted/Undiscounted/Policy Cost by Period) and how are they related?

Many thanks
Franklyn

**Comment by pkyle** [comment]
Franklyn,
`policy cost by period` is an annual flow, indicated in millions of dollars per year.
`undiscounted policy cost` is a lump sum aggregate cost, indicated in millions of dollars. To calculate it from the former query, you'll need to linearly interpolate from the 5-year timesteps to all years.
`discounted policy cost` is determined from the policy costs in each year, discounted at an exogenous rate. The default rate is 0.05, but can be over-ridden by reading in a `discountRate` in the `doubles` section of your `configuration.xml`.
