### ISSUE TITLE
Question -- GCAM's modeling of advanced future tech 

### ISSUE THREAD

**Issue by lucasingamba** [JGCRI/gcam-core#9]
Hi all,

I was wondering if you could help me with an understanding of the capabilities of GCAM. I'm a statistical fellow at the DOE's ARPA-E,  and I'm trying to produce impact estimations of the potential effect of our tech on emissions reductions over time. I'm interested in constructing a series of simulations to "experimentally" investigate what-if scenarios. E.g., if by 2030, electric car sales increase to 25% of new LD vehicle sales each year, what do the emissions of the LD fleet look like? What does it look like if EVs were to increase to 50% of new sales?  75%? 

The current iteration of my models are weakly agent-based, meaning they simulate an atomized representation of the sector that they pertain to. Several drawbacks to yours (and please correct me if my understanding is wrong) -- yours includes interactions between sectors and yours have cost present.  Mine have neither. My sims force a certain amount of this new tech into the world, whereas it seems to me that you set up cost and decision functions, and then let the model choose a certain amount of the new tech as appropriate. Would love to converse with someone about the relative merits of a simpler, more sparse model and a more comprehensive one like yours, and also hear the extent to which GCAM can accommodate the modeling of tech specifically. 

One final extension to this -- wondering if GCAM does a good job modeling advancements in tech that may have many indirect positives. For instance, cheaper batteries == more potential for solar == lower prices. Similarly, more EVs on the grid == more potential for batteries == more potential for solar.

Feel free to point me to any papers you've written or respond directly to my email at lucas.spangher@hq.doe.gov. Thank you!

**Comment by d3y419** [comment]
I wrote my thesis on this subject. Here is a most relevant paper from the thesis:
http://www.sciencedirect.com/science/article/pii/S0140988310001866
