### ISSUE TITLE
Execution Error for GCAM 5.2

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#90]
Hi 

I just installed GCAM 5.2 on windows and I get the error shown below. 
Any help will be appreciated.

![image](https://user-images.githubusercontent.com/34580273/70721153-18e3bc80-1cc3-11ea-947f-e32f09a07f55.png)

**Comment by pralitp** [comment]
To follow up, this message is in reference to needing to install the Visual Studio Redistributable package which can be found here:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

While it has always been the case that the Windows users package of GCAM has required it to be installed what changed in GCAM 5.2 is we updated version of Visual Studio so users will need to install a newer version of the redistributable as well.

We will update the documentation to clarify.
