### ISSUE TITLE
Shapefiles for water basins with updated GCAM 5.2 naming conventions.

### ISSUE THREAD

**Issue by jayfuhrman** [JGCRI/gcam-core#94]

**Comment by jayfuhrman** [comment]
Is there an updated shapefile for the GCAM water basins with the new naming convention? Alternatively, is there a file that could be used to map the old to the new basin names (e.g., Adriatic_Sea_Greece_Black_Sea_Coast, to AdrBlkSea)?  

![image001](https://user-images.githubusercontent.com/48569483/74454567-1849dc80-4e52-11ea-84d1-b7ac7a108c7e.png)

**Comment by pkyle** [comment]
Not sure about the shapefile, but there is a translation between the long and short basin names available in the following file:
`input/gcamdata/inst/extdata/water/basin_to_country_mapping.csv`

**Comment by jayfuhrman** [comment]
Thank you!
