### ISSUE TITLE
Regional Temperatures from GCAM global mean temperature

### ISSUE THREAD

**Issue by fkanyako** [JGCRI/gcam-core#96]
Hi,
How can I estimate regional temperatures from the global mean temperature GCAM output? 
Has anyone done this? any advice??

Thank you

**Comment by kvcalvin** [comment]
@fkanyako: GCAM by itself only calculates global mean temperature. You could use pattern scaling to generate spatial temperature. Here is a paper describing an open source library/method for this: https://essd.copernicus.org/articles/9/281/2017/
