### ISSUE TITLE
Cement coefficients of 1?

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#99]
Hi, hoping to get some clarity on the cement.xml file. In the global-technology-database, it looks like all fuels used for process heating have a coefficient of 1, which would imply a 100% conversion from fuel to heat. Am I misinterpreting this?

Thank you.

**Comment by pkyle** [comment]
Process heat cement is a an intermediate sector, intended to compete the fuels that are providing heat for the cement production technology. The cement supplysector/subsector/technology takes 3 inputs, with fixed coefficients on each: process heat cement (about 0.004 GJ of heat per kg of cement), electricity (about 0.0005 GJ of electricity per kg of cement), and limestone (about 1.5 kg of limestone per kg of cement). These inputs are non-substitutable, or "Leonteif" inputs. In order to have competition between the fuels that are providing heat, we have the additional "process heat cement" sector. There's no fuel-level differentiation on the energy intensity (all fuels are implicitly assumed to require ~4 GJ per tonne of cement) as there was no such distinction in the source data used.

**Comment by robbieorvis** [comment]
Hi @pkyle, thanks for this.

Based on what you describe, the way to improve the energy efficiency of cement production (in particular, lowering the demand for process heating) in that case is to decrease the minicam-energy-input coefficient for process heat cement in future years, right? I've done that for other sectors, so seems easy enough.

(Also, just for background, but it would be interesting to add hydrogen as a fuel for process heating for later years).

**Comment by pkyle** [comment]
Yes, that is what I'd recommend. Be aware that the cement.xml file uses the `global-technology-database` for both the coefficients of the `cement` production technology (in future periods), and the coefficients of the `process heat cement` technologies (in all periods, though the values are 1 in all years). If you change the global technology defaults, the changes will be applied to all regions. To do something region-specific, you can expand on the existing table `L2321.StubTechCoef_cement` in zchunk_L2321.cement.R. At present that table only has values in the calibration years, but it can be expanded to all years if you want to prescribe region-specific energy intensity pathways.
As for hydrogen, go for it! Let me know off-line if you run into any issues; basically you just want to include it in all of the subsector- and technology-level tables that start `energy/A321.*`, and make sure the share-weights are zeroes in the calibration years and any other years you don't want it to be available.

**Comment by robbieorvis** [comment]
Thanks @pkyle.

FYI, for these types of things, I've been using @rjplevin's pygcam, which is extremely useful. No need to use the data system to edit the files. Users can just feed a single line pygcam which can modify and insert efficiency values (or e.g. coefficients for process heat) and create a modified cement.xml file that is then referenced in the config file. Saves a lot of time and I've been working with @rjplevin to add a bunch of policies to pygcam.

Anyway thanks as always for the answers!

**Comment by Swati0201** [comment]
Hi I am using GCAM6 and can see that in the future period fertilizer and feed coefficients are fixed. I want to study the impact of biochar technology which reduces the fertiliser requirement by 20% and hence helps in emission reduction. Similarly, how to change the feed coefficient in the livestock sector. How can one go around it? @pkyle @realxinzhao

**Comment by realxinzhao** [comment]
@Swati0201  
Yes, the N fertilizer input-output coefficient is fixed over time. You can lower it in future periods to represent a more efficient use of the N fertilizer or smaller N fertilizer demand in a tech (e.g. when biochar is applied). 
The `coefficient` is in `ag_Fert_IRR_MGMT.xml` or `ag_cost_IRR_MGMT.xml` (might be a bug before if it appears in both; the latter read in the configuration file would overwrite the early one).

Similarly, there are coefficients for mean feed conversion in `an_input.xml`, which is currently constant in the GCAM core. There might be developments later to improve that. We have a recent study (under review & livestock was not a focus) that included growth in feed conversion efficiency based on some information from the IMAGE model. Happy to learn more if you have better data/assumptions/sources. Thanks.

**Comment by pkyle** [comment]
Thanks Xin, and I just wanted to add, in terms of how to do this, the assumptions for both N fertilizer input-output coefficients and non-land variable costs (which also will presumably need to be modified to represent biochar use) are read at the level of the ag production technology, and the relevant XML file is >200MB, so it's not something that can be practically changed by hand. So I'd recommend working within gcamdata where the relevant data tables are `L2062.AgCoef_Fert_ag_irr_mgmt` and `L2062.AgCost_ag_irr_mgmt_adj`.
